Repository woowacourse-teams/2024-haeng-dong, pull requests merged in 2024-07, with the labels that each got.

#37 [FE] client 설정 수정
  client/.eslintrc.json
  client/eslint.config.mjs
  client/package-lock.json
  client/package.json
  client/src/components/Modal/Modal.tsx
  client/src/components/Modal/SetActionModalContent/SetActionModalContent.tsx
  client/src/components/Modal/SetActionModalContent/SetPurchase.tsx
  client/src/components/Modal/SetInitialParticipants/SetInitialParticipants.tsx
  client/src/components/Switch/Switch.tsx
  client/src/index.tsx
  client/src/pages/CompleteCreateEvent/CompleteCreateEvent.tsx
  client/src/pages/CreateEvent/CreateEvent.tsx
  client/src/pages/Event/Event.tsx
  client/src/pages/Main/Main.tsx
  client/src/router.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: 🖥️ FE, ⚙️ feat, 🛠️ Setting

#38 [FE] client 설정 수정
  client/.eslintrc.json
  client/eslint.config.mjs
  client/package-lock.json
  client/package.json
  client/src/components/Modal/Modal.tsx
  client/src/components/Modal/SetActionModalContent/SetActionModalContent.tsx
  client/src/components/Modal/SetActionModalContent/SetPurchase.tsx
  client/src/components/Modal/SetInitialParticipants/SetInitialParticipants.tsx
  client/src/components/Switch/Switch.tsx
  client/src/index.tsx
  client/src/pages/CompleteCreateEvent/CompleteCreateEvent.tsx
  client/src/pages/CreateEvent/CreateEvent.tsx
  client/src/pages/Event/Event.tsx
  client/src/pages/Main/Main.tsx
  client/src/router.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: 🖥️ FE, ⚙️ feat, 🛠️ Setting

#40 [BE] 프로젝트 엔티티 작성
  server/.gitignore
  server/.gitkeep
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/server/haengdong/ServerApplication.java
  server/src/main/java/server/haengdong/domain/Action.java
  server/src/main/java/server/haengdong/domain/BillAction.java
  server/src/main/java/server/haengdong/domain/Event.java
  server/src/main/java/server/haengdong/domain/EventStep.java
  server/src/main/java/server/haengdong/domain/MemberAction.java
  server/src/main/java/server/haengdong/domain/MemberActionStatus.java
  server/src/main/resources/application.properties
  server/src/test/java/server/haengdong/ServerApplicationTests.java
Labels: ⌨️ BE, ⚙️ feat

#42 [BE] CI/CD 파이프라인 구축
  .github/workflows/backend-pull-request.yml
  .github/workflows/backend-push.yml
  server/Dockerfile
Labels: ⌨️ BE, ⚙️ feat

#41 [BE] 행사 생성 기능 구현
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/application/request/EventAppRequest.java
  server/src/main/java/server/haengdong/application/response/EventAppResponse.java
  server/src/main/java/server/haengdong/domain/Event.java
  server/src/main/java/server/haengdong/domain/EventTokenProvider.java
  server/src/main/java/server/haengdong/persistence/EventRepository.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/java/server/haengdong/presentation/request/EventSaveRequest.java
  server/src/test/java/server/haengdong/application/EventServiceTest.java
  server/src/test/java/server/haengdong/presentation/EventControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#46 [FE] 디자인 시스템 수정
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/assets/arrow.svg
  HDesign/src/assets/index.ts
  HDesign/src/assets/inputDelete.svg
  HDesign/src/components/BillItem/BillItem.style.ts
  HDesign/src/components/BillItem/BillItem.tsx
  HDesign/src/components/BillItem/BillItem.type.ts
  HDesign/src/components/DragHandleItem/DragHandleItem.stories.tsx
  HDesign/src/components/DragHandleItem/DragHandleItem.style.ts
  HDesign/src/components/DragHandleItem/DragHandleItem.tsx
  HDesign/src/components/ExpenseList/ExpenseList.stories.tsx
  HDesign/src/components/ExpenseList/ExpenseList.style.ts
  HDesign/src/components/ExpenseList/ExpenseList.tsx
  HDesign/src/components/ExpenseList/ExpenseList.type.ts
  HDesign/src/components/Flex/Flex.tsx
  HDesign/src/components/Flex/Flex.type.ts
  HDesign/src/components/InOutItem/InOutItem.stories.tsx
  HDesign/src/components/InOutItem/InOutItem.tsx
  HDesign/src/components/InOutItem/InOutItem.type.ts
  HDesign/src/components/Input/Input.stories.tsx
  HDesign/src/components/Input/Input.style.ts
  HDesign/src/components/Input/Input.tsx
  HDesign/src/components/Input/Input.type.ts
  HDesign/src/components/StepItem/StepItem.style.ts
  HDesign/src/components/StepItem/StepItem.tsx
  HDesign/src/components/Switch/Switch.stories.tsx
  HDesign/src/components/Switch/Switch.style.ts
  HDesign/src/components/Switch/Switch.tsx
  HDesign/src/components/Switch/Switch.type.ts
  HDesign/src/components/Switch/useSwitch.ts
  HDesign/src/components/Tab/Tab.stories.tsx
  HDesign/src/components/Tab/Tab.style.ts
  HDesign/src/components/Tab/Tab.tsx
  HDesign/src/components/Tab/Tab.type.ts
  HDesign/src/components/Text/Text.style.ts
  HDesign/src/components/Text/Text.tsx
  HDesign/src/components/Text/Text.type.ts
  HDesign/src/components/TextButton/TextButton.stories.tsx
  HDesign/src/components/TextButton/TextButton.style.ts
  HDesign/src/components/TextButton/TextButton.tsx
  HDesign/src/components/TextButton/TextButton.type.ts
  HDesign/src/components/Title/Title.stories.tsx
  HDesign/src/components/Title/Title.style.ts
  HDesign/src/components/Title/Title.tsx
  HDesign/src/components/Title/Title.type.ts
  HDesign/src/components/TopNav/TopNav.stories.ts
  HDesign/src/components/TopNav/TopNav.style.ts
  HDesign/src/components/TopNav/TopNav.tsx
  HDesign/src/components/TopNav/TopNav.type.ts
  HDesign/src/token/colors.ts
  HDesign/src/types/strictPropsWithChildren.ts
  HDesign/src/utils/ return str.replace(/([a-z])([A-Z])/changeCamelCaseToKebabCase.ts
Labels: 🖥️ FE, ⚙️ feat, 🎨 Design

#56 [BE] PR 후 테스트 리포트 발행 기능 추가
  .github/workflows/backend-pull-request.yml
Labels: ⌨️ BE, ⚙️ feat

#45 [BE] 지출로그 추가 기능 구현
  server/build.gradle
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/application/request/BillActionAppRequest.java
  server/src/main/java/server/haengdong/domain/Action.java
  server/src/main/java/server/haengdong/domain/BillAction.java
  server/src/main/java/server/haengdong/persistence/ActionRepository.java
  server/src/main/java/server/haengdong/persistence/BillActionRepository.java
  server/src/main/java/server/haengdong/persistence/EventRepository.java
  server/src/main/java/server/haengdong/presentation/BillActionController.java
  server/src/main/java/server/haengdong/presentation/request/BillActionSaveRequest.java
  server/src/main/java/server/haengdong/presentation/request/BillActionsSaveRequest.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
  server/src/test/java/server/haengdong/ServerApplicationTests.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/domain/ActionTest.java
  server/src/test/java/server/haengdong/domain/BillActionTest.java
  server/src/test/java/server/haengdong/presentation/BillActionControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#47 [BE] 인원 변동 기능 구현
  server/src/main/java/server/haengdong/application/MemberActionFactory.java
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/application/request/MemberActionSaveAppRequest.java
  server/src/main/java/server/haengdong/application/request/MemberActionsSaveAppRequest.java
  server/src/main/java/server/haengdong/domain/EventStep.java
  server/src/main/java/server/haengdong/domain/MemberAction.java
  server/src/main/java/server/haengdong/domain/MemberActionStatus.java
  server/src/main/java/server/haengdong/domain/MemberGroupIdProvider.java
  server/src/main/java/server/haengdong/persistence/ActionRepository.java
  server/src/main/java/server/haengdong/persistence/EventRepository.java
  server/src/main/java/server/haengdong/persistence/MemberActionRepository.java
  server/src/main/java/server/haengdong/presentation/MemberActionController.java
  server/src/main/java/server/haengdong/presentation/request/MemberActionSaveRequest.java
  server/src/main/java/server/haengdong/presentation/request/MemberActionsSaveRequest.java
  server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java
  server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
  server/src/test/java/server/haengdong/presentation/EventControllerTest.java
  server/src/test/java/server/haengdong/presentation/MemberActionControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#68 [FE] api wrapping
  client/src/apis/fetcher.ts
Labels: 🖥️ FE, ⚙️ feat

#74 [FE] @svgr/webpack 플러그인 설치
  client/package-lock.json
  client/package.json
  client/webpack.config.js
Labels: 🖥️ FE, ⚙️ feat, 🛠️ Setting

#75 [BE] 행사 정보 조회 기능 구현
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/application/response/EventDetailAppResponse.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/java/server/haengdong/presentation/response/EventDetailResponse.java
  server/src/test/java/server/haengdong/application/EventServiceTest.java
  server/src/test/java/server/haengdong/presentation/EventControllerTest.java
Labels: ⌨️ BE

#86 [BE] 요청 데이터가 맵핑되지 않는 문제 해결
  server/src/main/java/server/haengdong/presentation/EventController.java
Labels: ⌨️ BE, 🚨 bug

#70 [BE] 현재 참여 인원 조회
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/application/response/CurrentMemberAppResponse.java
  server/src/main/java/server/haengdong/domain/action/CurrentMembers.java
  server/src/main/java/server/haengdong/presentation/MemberActionController.java
  server/src/main/java/server/haengdong/presentation/response/CurrentMemberResponse.java
  server/src/main/java/server/haengdong/presentation/response/CurrentMembersResponse.java
  server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
  server/src/test/java/server/haengdong/domain/action/CurrentMembersTest.java
  server/src/test/java/server/haengdong/presentation/MemberActionControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#51 [FE] 탭 컴포넌트 height 소수점 문제
  HDesign/src/components/Tab/Tab.style.ts
Labels: 🖥️ FE, 🚨 bug

#71 [FE] 배포, CI 및 테스트 전략 수립 #32
  .github/workflows/frontend-pll-request.yml
  client/eslint.config.mjs
  client/package-lock.json
  client/package.json
  client/src/components/Modal/SetActionModalContent/SetActionModalContent.tsx
  client/src/components/Modal/SetActionModalContent/SetPurchase.tsx
  client/src/pages/CompleteCreateEvent/CompleteCreateEvent.tsx
  client/src/pages/CreateEvent/CreateEvent.tsx
  client/src/pages/Event/Event.tsx
  client/src/pages/Main/Main.tsx
  client/src/router.tsx
  client/tsconfig.json
Labels: 🖥️ FE, ⚙️ feat

#87 [FE] 행사 생성 페이지 구현
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/apis/fetcher.ts
  client/src/apis/requestPostEvent.ts
  client/src/constants/routerUrls.ts
  client/src/index.css
  client/src/pages/CompleteCreateEvent/index.ts
  client/src/pages/Create/Complete.tsx
  client/src/pages/Create/Name.tsx
  client/src/pages/Create/index.ts
  client/src/pages/CreateEvent/CreateEvent.tsx
  client/src/pages/CreateEvent/index.ts
  client/src/pages/Main/Main.tsx
  client/src/router.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: 🖥️ FE, ⚙️ feat

#88 [FE] 행사 홈 페이지 구현
  client/package-lock.json
  client/package.json
  client/src/apis/baseUrl.ts
  client/src/apis/request/bill.ts
  client/src/apis/request/event.ts
  client/src/apis/request/member.ts
  client/src/apis/request/report.ts
  client/src/apis/request/stepList.ts
  client/src/apis/tempPrefix.ts
  client/src/apis/withEventId.type.ts
  client/src/components/MemberReportList/MemberReportList.tsx
  client/src/components/StepList/StepList.tsx
  client/src/constants/routerUrls.ts
  client/src/hooks/useSearchMemberReportList/useSearchMemberReportList.tsx
  client/src/hooks/useStepList/useStepList.tsx
  client/src/mocks/memberReportSearchList.json
  client/src/mocks/stepList.json
  client/src/pages/CreateEvent/CreateEvent.tsx
  client/src/pages/Home/HomeContent.tsx
  client/src/pages/Home/HomeLayout.tsx
  client/src/pages/Home/index.ts
  client/src/router.tsx
  client/src/types/stepList.ts
  client/webpack.config.js
Labels: 🖥️ FE, ⚙️ feat

#78 [FE] 현재 참여자 검색 component 생성
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/Input/Input.style.ts
  HDesign/src/components/Search/Search.stories.tsx
  HDesign/src/components/Search/Search.style.ts
  HDesign/src/components/Search/Search.tsx
  HDesign/src/components/Search/useSearch.ts
  HDesign/src/components/Title/Title.style.ts
  HDesign/src/components/TopNav/TopNav.style.ts
  HDesign/src/index.tsx
  HDesign/src/layouts/MainLayout.tsx
  HDesign/tsconfig.json
Labels: 🖥️ FE, ⚙️ feat

#90 [BE] CORS 설정
  server/src/main/java/server/haengdong/config/WebConfig.java
  server/src/main/resources/application.yml
  server/src/test/resources/application.yml
Labels: ⌨️ BE, ⚙️ feat

#92 [BE] 행사 커스텀 예외 처리
  server/src/main/java/server/haengdong/HaengdongApplication.java
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/application/MemberActionFactory.java
  server/src/main/java/server/haengdong/exception/ErrorResponse.java
  server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/main/java/server/haengdong/exception/HaengdongException.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java
Labels: ⌨️ BE, ⚙️ feat

#77 [BE] 참여자별 정산 현황 조회 기능 구현
  server/src/main/java/server/haengdong/application/ActionService.java
  server/src/main/java/server/haengdong/application/response/MemberBillReportAppResponse.java
  server/src/main/java/server/haengdong/domain/action/BillAction.java
  server/src/main/java/server/haengdong/domain/action/MemberAction.java
  server/src/main/java/server/haengdong/domain/action/MemberBillReports.java
  server/src/main/java/server/haengdong/presentation/ActionController.java
  server/src/main/java/server/haengdong/presentation/response/MemberBillReportResponse.java
  server/src/main/java/server/haengdong/presentation/response/MemberBillReportsResponse.java
  server/src/test/java/server/haengdong/application/ActionServiceTest.java
  server/src/test/java/server/haengdong/domain/action/MemberBillReportsTest.java
  server/src/test/java/server/haengdong/presentation/ActionControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#98 [BE] api 명세에서 행사 url을 표현하는 용어와 전달 방식 수정
  server/src/main/java/server/haengdong/presentation/ActionController.java
  server/src/main/java/server/haengdong/presentation/BillActionController.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/java/server/haengdong/presentation/MemberActionController.java
  server/src/main/java/server/haengdong/presentation/response/EventResponse.java
  server/src/test/java/server/haengdong/presentation/EventControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#102 [BE] 기본 프로파일에서 DB를 MySQL을 H2로 변경
  server/src/main/resources/application.yml
Labels: ⌨️ BE

#100 [BE] 지출 내역 생성 및 현재 참여 인원 조회 예외 메시지 변경
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/domain/action/BillAction.java
  server/src/main/java/server/haengdong/presentation/request/BillActionSaveRequest.java
  server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
  server/src/test/java/server/haengdong/domain/action/BillActionTest.java
Labels: ⌨️ BE, 🚧 refactor

#106 [BE] 참여자별 정산 현황 조회 API 예외 메시지 추가
  server/src/main/java/server/haengdong/application/ActionService.java
  server/src/test/java/server/haengdong/application/ActionServiceTest.java
Labels: ⌨️ BE, 🚧 refactor

#103 [BE] 행사 생성 API 예외 메세지 및 DTO 검증 애너테이션 추가
  server/src/main/java/server/haengdong/domain/event/Event.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/java/server/haengdong/presentation/request/EventSaveRequest.java
  server/src/test/java/server/haengdong/domain/event/EventTest.java
Labels: ⌨️ BE, 🚧 refactor

#111 [BE] 예외에서 정의한 메세지를 꺼내지 못하는 오류 해결
  server/src/main/java/server/haengdong/exception/ErrorResponse.java
  server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java
Labels: ⌨️ BE, 🚨 bug

#114 [FE] 퍼블리싱된 페이지 매끄럽게 연결
  client/package-lock.json
  client/package.json
  client/src/constants/routerUrls.ts
  client/src/pages/Create/Complete.tsx
  client/src/pages/Create/Name.tsx
  client/src/pages/Event/Event.tsx
Labels: 🖥️ FE, ⚙️ feat

#117 [BE] 인원 변동 요청 형태 변경
  server/src/main/java/server/haengdong/presentation/request/MemberActionSaveRequest.java
  server/src/main/java/server/haengdong/presentation/request/MemberActionsSaveRequest.java
  server/src/test/java/server/haengdong/presentation/MemberActionControllerTest.java
Labels: ⌨️ BE, 🚧 refactor

#76 [BE] 액션 이력 조회 기능 구현
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/application/response/ActionAppResponse.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/java/server/haengdong/presentation/response/ActionResponse.java
  server/src/main/java/server/haengdong/presentation/response/ActionsResponse.java
  server/src/main/java/server/haengdong/presentation/response/StepResponse.java
  server/src/test/java/server/haengdong/application/EventServiceTest.java
  server/src/test/java/server/haengdong/presentation/response/StepResponseTest.java
Labels: ⌨️ BE, ⚙️ feat

#120 [FE] frontend yml lint 과정 수정
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/workflows/frontend-pull-request.yml
  client/package.json
Labels: 🖥️ FE, ⚙️ feat, 🛠️ Setting

#122 [BE] 액션 이력이 없는 경우 빈 리스트 반환
  server/src/main/java/server/haengdong/presentation/response/StepResponse.java
Labels: ⌨️ BE, 🚨 bug

#124 [BE] 액션 이력 조회 오류 수정
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/domain/action/MemberActionStatus.java
  server/src/main/java/server/haengdong/presentation/response/StepResponse.java
Labels: ⌨️ BE, 🚨 bug

#126 [BE] StepResponse 로직 수정
  server/src/main/java/server/haengdong/presentation/response/StepResponse.java
Labels: ⌨️ BE, 🚨 bug

#128 [BE] Gradle, Docker 캐싱을 위한 Feature/#121 test
  .github/workflows/backend-pull-request.yml
  .github/workflows/backend-push.yml
  server/src/main/java/server/haengdong/HaengdongApplication.java
Labels: ⌨️ BE, ⚙️ feat

#131 gradle build test
  .github/workflows/backend-push.yml
  server/Dockerfile
Labels: ⌨️ BE, ⚙️ feat

#133 revert: gradle cache, docker cache
  .github/workflows/backend-pull-request.yml
  .github/workflows/backend-push.yml
  server/src/main/java/server/haengdong/HaengdongApplication.java
Labels: ⌨️ BE

#134 [BE] 애플리케이션 도커 포트 번호 수정
  .github/workflows/backend-push.yml
Labels: ⌨️ BE, ⚙️ feat

#138 [BE] Docker 빌드 성능 개선
  .github/workflows/backend-push.yml
  server/Dockerfile
Labels: ⌨️ BE, 🚧 refactor

#110 [BE] 참여자 정산 현황 로직 리펙토링
  server/src/main/java/server/haengdong/application/ActionService.java
  server/src/main/java/server/haengdong/domain/action/CurrentMembers.java
  server/src/main/java/server/haengdong/domain/action/MemberAction.java
  server/src/main/java/server/haengdong/domain/action/MemberBillReport.java
  server/src/test/java/server/haengdong/domain/action/CurrentMembersTest.java
  server/src/test/java/server/haengdong/domain/action/MemberBillReportTest.java
Labels: ⌨️ BE, 🚧 refactor

#81 [FE] storybook chromatic 배포
  .github/workflows/design-pull-request.yml
  HDesign/eslint.config.mjs
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/BillItem/BillItem.style.ts
  HDesign/src/components/BillItem/BillItem.tsx
  HDesign/src/components/DragHandleItem/DragHandleItem.style.ts
  HDesign/src/components/DragHandleItem/DragHandleItem.tsx
  HDesign/src/components/ExpenseList/ExpenseList.style.ts
  HDesign/src/components/ExpenseList/ExpenseList.tsx
  HDesign/src/components/Flex/Flex.tsx
  HDesign/src/components/IconButton/IconButton.tsx
  HDesign/src/components/InOutItem/InOutItem.style.ts
  HDesign/src/components/InOutItem/InOutItem.tsx
  HDesign/src/components/Input/Input.style.ts
  HDesign/src/components/Search/Search.stories.tsx
  HDesign/src/components/Search/Search.style.ts
  HDesign/src/components/Search/Search.tsx
  HDesign/src/components/StepItem/StepItem.style.ts
  HDesign/src/components/StepItem/StepItem.tsx
  HDesign/src/components/Switch/Switch.tsx
  HDesign/src/components/Tab/Tab.stories.tsx
  HDesign/src/components/Tab/Tab.style.ts
  HDesign/src/components/Tab/Tab.tsx
  HDesign/src/components/TextButton/TextButton.style.ts
  HDesign/src/components/TextButton/TextButton.tsx
  HDesign/src/components/TopNav/TopNav.stories.ts
  HDesign/src/components/TopNav/TopNav.tsx
  HDesign/src/layouts/MainLayout.tsx
Labels: 🖥️ FE, 🎨 Design

#137 [FE] 2차 스프린트 API 연결
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/apis/fetcher.ts
  client/src/apis/request/bill.ts
  client/src/apis/request/event.ts
  client/src/apis/request/member.ts
  client/src/apis/request/report.ts
  client/src/apis/request/stepList.ts
  client/src/apis/requestPostEvent.ts
  client/src/components/MemberReportList/MemberReportList.tsx
  client/src/components/Modal/SetActionModalContent/SetActionModalContent.tsx
  client/src/components/Modal/SetActionModalContent/SetPurchase.tsx
  client/src/components/Modal/SetActionModalContent/UpdateParticipants.tsx
  client/src/components/Modal/SetInitialParticipants/SetInitialParticipants.tsx
  client/src/components/StepList/StepList.tsx
  client/src/constants/routerUrls.ts
  client/src/hooks/useDynamicInputPairs.tsx
  client/src/hooks/useEventId/useEventId.tsx
  client/src/hooks/useNavSwitch.tsx
  client/src/hooks/useSearchMemberReportList/useSearchMemberReportList.tsx
  client/src/hooks/useStepList/type.ts
  client/src/hooks/useStepList/useStepList.tsx
  client/src/index.css
  client/src/pages/Create/Complete.tsx
  client/src/pages/Create/Name.tsx
  client/src/pages/CreateEvent/CreateEvent.tsx
  client/src/pages/Event/Admin/Admin.style.ts
  client/src/pages/Event/Admin/Admin.tsx
  client/src/pages/Event/Admin/index.ts
  client/src/pages/Event/Event.tsx
  client/src/pages/Event/EventLayout.tsx
  client/src/pages/Event/Home/Home.tsx
  client/src/pages/Event/Home/index.ts
  client/src/pages/Event/index.ts
  client/src/pages/Home/HomeContent.tsx
  client/src/pages/Home/HomeLayout.tsx
  client/src/pages/Home/index.ts
  client/src/pages/Main/Main.tsx
  client/src/router.tsx
  client/src/type.d.ts
Labels: 🖥️ FE, ⚙️ feat

#152 [BE]: gradle 빌드 실패 버그
  .github/workflows/backend-pull-request.yml
  .github/workflows/backend-push.yml
Labels: ⌨️ BE, 🚨 bug

#162 [FE] 스프린트3 디자인 수정
  .github/workflows/design-pull-request.yml
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/assets/error.svg
  HDesign/src/assets/index.ts
  HDesign/src/assets/trash.svg
  HDesign/src/components/Button/Button.stories.tsx
  HDesign/src/components/Button/Button.style.ts
  HDesign/src/components/Button/Button.type.ts
  HDesign/src/components/ExpenseList/ExpenseList.tsx
  HDesign/src/components/FixedButton/FixedButton.stories.tsx
  HDesign/src/components/FixedButton/FixedButton.style.ts
  HDesign/src/components/FixedButton/FixedButton.tsx
  HDesign/src/components/FixedButton/FixedButton.type.ts
  HDesign/src/components/InOutItem/InOutItem.tsx
  HDesign/src/components/Input/Input.style.ts
  HDesign/src/components/Input/Input.tsx
  HDesign/src/components/Input/Input.type.ts
  HDesign/src/components/Input/useInput.ts
  HDesign/src/components/LabelInput/LabelInput.stories.tsx
  HDesign/src/components/LabelInput/LabelInput.style.ts
  HDesign/src/components/LabelInput/LabelInput.tsx
  HDesign/src/components/LabelInput/LabelInput.type.ts
  HDesign/src/components/Search/Search.stories.tsx
  HDesign/src/components/Toast/Toast.stories.tsx
  HDesign/src/components/Toast/Toast.style.ts
  HDesign/src/components/Toast/Toast.tsx
  HDesign/src/components/Toast/Toast.type.ts
  HDesign/src/components/Toast/useToast.ts
  HDesign/src/index.tsx
  HDesign/src/token/colors.ts
Labels: 🖥️ FE, ⚙️ feat, 🎨 Design

#165 [FE] branch 변경에 따른 github workflow 수정
  .github/workflows/design-pull-request.yml
  .github/workflows/frontend-pull-request.yml
Labels: 🖥️ FE, 🛠️ Setting
