Repository woowacourse-teams/2024-haeng-dong, pull requests merged in 2024-10, with the labels that each got.

#682 [FE] 데스크탑에서 '정산하기' 버튼 margin 미적용
  client/src/components/ShareEventButton/ShareEventButton.tsx
Labels: 🖥️ FE, 🚨 bug

#686 [FE] 이벤트 페이지 api 호출 개선
  client/src/components/Loader/EventLoader.tsx
  client/src/router.tsx
Labels: 🖥️ FE, 🚧 refactor

#688 [FE] 토스 송금 기능 개선
  client/src/components/Design/components/BankSendButton/BankSend.stories.tsx
  client/src/components/Design/components/BankSendButton/BankSendButton.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.stories.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.type.ts
  client/src/hooks/useReportsPage.ts
Labels: 🖥️ FE, 🚧 refactor

#691 [FE] 계좌번호 수정이 되지 않는 문제
  client/src/hooks/useAccount.ts
Labels: 🚨 bug, 🔍 QC, High

#607 [FE] staleTime, gcTime 기본 값 설정
  client/src/components/QueryClientBoundary/QueryClientBoundary.tsx
Labels: 🖥️ FE, ⚙️ feat

#700 [BE] createdAt 설정을 위한 BaseEntity 적용
  server/src/main/java/server/haengdong/HaengdongApplication.java
  server/src/main/java/server/haengdong/config/JpaConfig.java
  server/src/main/java/server/haengdong/domain/BaseEntity.java
  server/src/main/java/server/haengdong/domain/bill/Bill.java
  server/src/main/java/server/haengdong/domain/bill/BillDetail.java
  server/src/main/java/server/haengdong/domain/event/Event.java
  server/src/main/java/server/haengdong/domain/event/EventImage.java
  server/src/main/java/server/haengdong/domain/member/Member.java
Labels: ⌨️ BE, ⚙️ feat

#714 [BE] 영수증 이미지 업로드 기능 추가
  .gitignore
  server/build.gradle
  server/src/docs/asciidoc/event.adoc
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/application/ImageService.java
  server/src/main/java/server/haengdong/application/response/BillAppResponse.java
  server/src/main/java/server/haengdong/application/response/EventImageAppResponse.java
  server/src/main/java/server/haengdong/application/response/ImageNameAppResponse.java
  server/src/main/java/server/haengdong/application/response/MemberAppResponse.java
  server/src/main/java/server/haengdong/application/response/MemberDepositAppResponse.java
  server/src/main/java/server/haengdong/application/response/MemberSaveAppResponse.java
  server/src/main/java/server/haengdong/application/response/MembersSaveAppResponse.java
  server/src/main/java/server/haengdong/application/response/StepAppResponse.java
  server/src/main/java/server/haengdong/config/S3Config.java
  server/src/main/java/server/haengdong/domain/event/EventImage.java
  server/src/main/java/server/haengdong/domain/event/EventImageRepository.java
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/java/server/haengdong/presentation/admin/AdminEventController.java
  server/src/main/java/server/haengdong/presentation/request/BillDetailUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/request/BillDetailsUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/request/BillUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/request/EventLoginRequest.java
  server/src/main/java/server/haengdong/presentation/request/MemberNameUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/request/MemberNamesUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/request/MembersSaveRequest.java
  server/src/main/java/server/haengdong/presentation/response/BillResponse.java
  server/src/main/java/server/haengdong/presentation/response/EventImageResponse.java
  server/src/main/java/server/haengdong/presentation/response/EventImagesResponse.java
  server/src/main/java/server/haengdong/presentation/response/MemberSaveResponse.java
  server/src/main/java/server/haengdong/presentation/response/MembersSaveResponse.java
  server/src/main/java/server/haengdong/presentation/response/StepResponse.java
  server/src/main/java/server/haengdong/presentation/response/StepsResponse.java
  server/src/main/resources/application.yml
  server/src/test/java/server/haengdong/application/EventServiceTest.java
  server/src/test/java/server/haengdong/docs/AdminEventControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
  server/src/test/java/server/haengdong/presentation/ControllerTestSupport.java
  server/src/test/java/server/haengdong/presentation/EventControllerTest.java
  server/src/test/java/server/haengdong/presentation/admin/AdminEventControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#722 [BE] 행사 이미지 추가, 조회, 삭제 Rest Docs 추가
  server/src/docs/asciidoc/event.adoc
Labels: ⌨️ BE, ⚙️ feat

#696 [FE] 검색엔진 최적화를 위한 meta 태그 작성
  client/index.html
Labels: 🖥️ FE, 🛠️ Setting

#697 [FE] TopNav 버튼 강조 및 계좌번호 접근 관련
  client/src/components/ShareEventButton/DesktopShareEventButton.tsx
  client/src/components/ShareEventButton/MobileShareEventButton.tsx
  client/src/components/ShareEventButton/ShareEventButton.tsx
  client/src/components/ShareEventButton/index.ts
  client/src/constants/routerUrls.ts
  client/src/hooks/queries/auth/useRequestPostAuthentication.ts
  client/src/hooks/queries/auth/useRequestPostLogin.ts
  client/src/hooks/useEventPageLayout.ts
  client/src/hooks/useShareEvent.ts
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/EventPage/AuthGate/index.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/router.tsx
  client/src/store/authStore.ts
Labels: 🖥️ FE, 🔍 QC

#701 [FE] 정산 초대 및 송금기능 타겟 환경에 따른 flow 개선
  client/src/components/Design/components/BankSendButton/BankSendButton.style.ts
  client/src/components/Design/components/BankSendButton/BankSendButton.tsx
  client/src/components/Design/components/Banner/Banner.stories.tsx
  client/src/components/Design/components/Banner/Banner.tsx
  client/src/components/Design/components/Banner/Banner.type.ts
  client/src/components/Design/components/Banner/index.ts
  client/src/components/Design/components/Chevron/Chevron.style.ts
  client/src/components/Design/components/Chevron/Chevron.tsx
  client/src/components/Design/components/ClickOutsideDetector/index.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.stories.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.type.ts
  client/src/components/Design/components/Flex/Flex.tsx
  client/src/components/Design/components/Flex/Flex.type.ts
  client/src/components/Design/components/Select/Select.stories.tsx
  client/src/components/Design/components/Select/Select.style.ts
  client/src/components/Design/components/Select/Select.tsx
  client/src/components/Design/components/Select/Select.type.ts
  client/src/components/Design/components/Select/SelectInput.style.ts
  client/src/components/Design/components/Select/SelectInput.tsx
  client/src/components/Design/components/Select/index.ts
  client/src/components/Design/components/Select/useSelect.ts
  client/src/components/Design/components/SendButton/SendButton.stories.tsx
  client/src/components/Design/components/SendButton/SendButton.style.ts
  client/src/components/Design/components/SendButton/SendButton.tsx
  client/src/components/Design/index.tsx
  client/src/components/Design/token/zIndex.ts
  client/src/constants/routerUrls.ts
  client/src/constants/sessionStorageKeys.ts
  client/src/hooks/useAdminPage.ts
  client/src/hooks/useReportsPage.ts
  client/src/hooks/useSendPage.ts
  client/src/hooks/useShareEvent.ts
  client/src/pages/ErrorPage/SendErrorPage/index.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/SendPage/index.tsx
  client/src/router.tsx
  client/src/utils/SessionStorage.ts
Labels: 🖥️ FE, ⚙️ feat

#709 [FE] Footer 구현
  client/src/components/Footer/Footer.style.ts
  client/src/components/Footer/Footer.tsx
  client/src/components/Footer/Footer.type.ts
  client/src/components/Footer/index.ts
  client/src/pages/EventPage/EventPageLayout.tsx
Labels: 🖥️ FE, ⚙️ feat

#713 [FE] 토스에서 은행 이름 인식하지 않는 버그
  client/src/components/Design/components/BankSelect/BankSelect.tsx
  client/src/constants/bank.ts
Labels: 🖥️ FE, 🚨 bug, 🔍 QC, High

#715 [FE] 멤버 추가할 때 버튼을 사용할 수 있도록 함
  client/src/components/Design/components/Banner/Banner.tsx
  client/src/components/Design/components/Button/Button.style.ts
  client/src/components/Design/components/Button/Button.type.ts
  client/src/components/Design/components/Dropdown/Dropdown.style.ts
  client/src/components/Design/components/ExpenseList/ExpenseList.tsx
  client/src/components/Design/components/Flex/Flex.tsx
  client/src/components/Design/components/Flex/Flex.type.ts
  client/src/components/Design/components/Input/Input.tsx
  client/src/hooks/useMembersStep.ts
  client/src/pages/AddBillFunnel/steps/MembersStep.tsx
Labels: 🖥️ FE, ⚙️ feat

#716 [FE] react-query 캐싱 적용으로 인해 발생한 버그 해결
  client/src/hooks/queries/bill/useRequestDeleteBill.ts
  client/src/hooks/queries/bill/useRequestPostBill.ts
  client/src/hooks/queries/bill/useRequestPutBill.ts
  client/src/hooks/queries/bill/useRequestPutBillDetails.ts
  client/src/hooks/queries/event/useRequestPostEvent.ts
  client/src/hooks/queries/member/useRequestDeleteMember.ts
  client/src/hooks/queries/member/useRequestPostMembers.ts
  client/src/hooks/queries/member/useRequestPutMembers.ts
Labels: 🖥️ FE, 🚨 bug

#720 [FE] toast.error, toast.none이어도 모두 toast.confirm으로 출력되는 문제
  client/src/hooks/useToast/toast.ts
  client/src/hooks/useToast/useToast.tsx
Labels: 🖥️ FE, 🚨 bug, Low

#723 [FE] 사진 업로드 기능
  client/src/GlobalStyle.ts
  client/src/apis/baseUrl.ts
  client/src/apis/request/images.ts
  client/src/assets/image/photoButton.svg
  client/src/components/Design/components/Carousel/Carousel.stories.tsx
  client/src/components/Design/components/Carousel/Carousel.style.ts
  client/src/components/Design/components/Carousel/Carousel.tsx
  client/src/components/Design/components/Carousel/Carousel.type.ts
  client/src/components/Design/components/Carousel/CarouselDeleteButton.tsx
  client/src/components/Design/components/Carousel/CarouselIndicator.tsx
  client/src/components/Design/components/Carousel/useCarousel.tsx
  client/src/components/Design/components/Flex/Flex.tsx
  client/src/components/Design/components/Flex/Flex.type.ts
  client/src/components/Design/components/Icon/Icon.style.ts
  client/src/components/Design/components/Icon/Icon.tsx
  client/src/components/Design/components/Icon/Icon.type.ts
  client/src/components/Design/components/Title/Title.style.ts
  client/src/components/Design/components/Title/Title.tsx
  client/src/components/Design/components/Title/Title.type.ts
  client/src/components/StepList/Step.tsx
  client/src/constants/queryKeys.ts
  client/src/constants/routerUrls.ts
  client/src/hooks/queries/event/useRequestPostEvent.ts
  client/src/hooks/queries/images/useRequestDeleteImages.ts
  client/src/hooks/queries/images/useRequestGetImages.ts
  client/src/hooks/queries/images/useRequestPostImages.ts
  client/src/hooks/useAddImagesPage.ts
  client/src/pages/AddImagesPage/AddImagesPage.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/EventPage/HomePage/HomePage.tsx
  client/src/pages/ImagesPage/ImagesPage.tsx
  client/src/router.tsx
  client/src/types/serviceType.ts
  client/src/utils/udpateMetaTag.ts
Labels: 🖥️ FE, ⚙️ feat

#719 [FE] 초대하기를 링크 공유와 카카오톡을 선택할 수 있도록 변경
  client/src/components/Design/components/Dropdown/ButtonBase.tsx
  client/src/components/Design/components/Dropdown/Dropdown.stories.tsx
  client/src/components/Design/components/Dropdown/Dropdown.style.ts
  client/src/components/Design/components/Dropdown/Dropdown.tsx
  client/src/components/Design/components/Dropdown/Dropdown.type.ts
  client/src/components/Design/components/Dropdown/DropdownButton.tsx
  client/src/components/Design/components/Dropdown/MeatballBase.tsx
  client/src/components/Design/components/Dropdown/useDropdown.ts
  client/src/components/Design/token/zIndex.ts
  client/src/components/ShareEventButton/DesktopShareEventButton.tsx
  client/src/components/ShareEventButton/MobileShareEventButton.tsx
  client/src/hooks/useShareEvent.ts
  client/src/pages/EventPage/EventPageLayout.tsx
Labels: 🖥️ FE, ⚙️ feat

#727 [FE] 사진 추가한 후 다시 접속 시 반영이 되지 않는 버그
  client/src/apis/fetcher.ts
  client/src/apis/request/images.ts
  client/src/hooks/queries/images/useRequestPostImages.ts
  client/src/hooks/useAddImagesPage.ts
Labels: 🖥️ FE, 🚨 bug, 🔍 QC, High

#735 [FE] 송금에서 데스크탑 환경은 복사하기밖에 보이지 않도록 수정
  client/src/components/Design/components/Select/Select.tsx
  client/src/components/Design/components/Select/useSelect.ts
  client/src/hooks/useSendPage.ts
Labels: 🖥️ FE, 🚨 bug, 🔍 QC, Medium

#737 [FE] 이미지 추가 및 조회 기능에서 발생하는 버그
  client/src/hooks/useAddImagesPage.ts
  client/src/pages/AddImagesPage/AddImagesPage.tsx
  client/src/pages/EventPage/HomePage/HomePage.tsx
Labels: 🖥️ FE, ⚙️ feat, 🔍 QC

#739 [FE] eventName에 따라 og태그가 변경되도록 수정
  client/index.html
  client/src/pages/EventPage/EventPageLayout.tsx
Labels: 🖥️ FE, ⚙️ feat

#749 [FE] 접근성 : 넘버 키패드 스크린리더 개선
  client/src/components/Design/components/NumberKeyboard/Keypad.tsx
  client/src/components/Design/components/NumberKeyboard/NumberKeyboard.tsx
  client/src/components/Design/components/NumberKeyboard/keypads.ts
Labels: 🖥️ FE, ⚙️ feat

#751 [FE] SelectBox 수정 + globalStyle 파란색 하이라이팅 제거
  client/src/GlobalStyle.ts
  client/src/components/Design/components/Select/SelectInput.tsx
Labels: 🖥️ FE, 🚨 bug

#756 [FE] 첫 지출내역 추가 시, 입금 상태 관리 Banner 띄우기
  client/src/constants/sessionStorageKeys.ts
  client/src/hooks/useAdminPage.ts
  client/src/hooks/useBanner.ts
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
Labels: 🖥️ FE, ⚙️ feat

#758 [FE] 접근성 개선 : 지출내역 추가 Flow의 Top
  client/src/components/Design/components/Top/Line.tsx
  client/src/components/Design/components/Top/Top.tsx
Labels: 🖥️ FE, 🚧 refactor

#759 [FE] 지출 내역 추가 플로우에서 참여 인원의 토큰의 x버튼에 낭독기 커서가 가도록 함
  client/package-lock.json
  client/package.json
  client/src/components/Design/components/Banner/Banner.tsx
  client/src/components/Design/components/ChipButton/ChipButton.tsx
  client/src/components/Design/components/DragHandleItem/DragHandleItem.stories.tsx
  client/src/components/Design/components/DragHandleItem/DragHandleItem.style.ts
  client/src/components/Design/components/DragHandleItem/DragHandleItem.tsx
  client/src/components/Design/components/DragHandleItem/DragHandleItem.type.ts
  client/src/components/Design/components/DragHandleItemContainer/DragHandleItemContainer.stories.tsx
  client/src/components/Design/components/DragHandleItemContainer/DragHandleItemContainer.style.ts
  client/src/components/Design/components/DragHandleItemContainer/DragHandleItemContainer.tsx
  client/src/components/Design/components/DragHandleItemContainer/DragHandleItemContainer.type.ts
  client/src/components/Design/components/Dropdown/MeatballBase.tsx
  client/src/components/Design/components/Icon/Icon.style.ts
  client/src/components/Design/components/Icon/Icon.tsx
  client/src/components/Design/components/Icon/Icon.type.ts
  client/src/components/Design/components/IconButton/IconButton.tsx
  client/src/components/Design/components/Input/Input.tsx
  client/src/components/Design/components/ListButton/ListButton.tsx
  client/src/components/Design/index.tsx
  client/src/hooks/useToast/useToast.test.tsx
  client/src/pages/EventPage/AdminPage/EventMember.tsx
  client/src/pages/MainPage/Nav/Nav.tsx
Labels: 🖥️ FE, ⚙️ feat, Medium

#760 [FE] v2.1.1에 맞춘 랜딩페이지 변경
  client/src/assets/image/chevronDownLarge.svg
  client/src/components/Design/components/Icon/Icon.style.ts
  client/src/components/Design/components/Icon/Icon.tsx
  client/src/components/Design/components/Text/Text.style.ts
  client/src/components/Design/components/Text/Text.tsx
  client/src/components/Design/components/Text/Text.type.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/Nav/Nav.tsx
  client/src/pages/MainPage/Section/AddBillSection.tsx
  client/src/pages/MainPage/Section/AddMemberSection.tsx
  client/src/pages/MainPage/Section/CreatorSection.tsx
  client/src/pages/MainPage/Section/DescriptionSection.tsx
  client/src/pages/MainPage/Section/FeatureSection.tsx
  client/src/pages/MainPage/Section/MainSection.tsx
Labels: 🖥️ FE, ⚙️ feat, 🎨 Design

#763 [FE] v2.1.1 배포 과정에서의 문제 해결
  client/src/components/Design/components/IconButton/IconButton.stories.tsx
  client/src/components/Design/components/NumberKeyboard/useNumberKeyboard.tsx
  client/src/hooks/useAdminPage.ts
Labels: 🖥️ FE, 🚨 bug, High

#767 [FE] 랜딩 페이지 디렉토리 구조 변경
  client/src/pages/MainPage/MainPage.style.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/Nav/Nav.style.ts
  client/src/pages/MainPage/Nav/Nav.tsx
  client/src/pages/MainPage/Nav/index.ts
  client/src/pages/MainPage/Section/DescriptionSection.tsx
  client/src/pages/MainPage/Section/DescriptionSection/DescriptionSection.style.ts
  client/src/pages/MainPage/Section/DescriptionSection/DescriptionSection.tsx
  client/src/pages/MainPage/Section/DescriptionSection/index.ts
  client/src/pages/MainPage/Section/FeatureSection.tsx
  client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/AutoCalculate.style.ts
  client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/AutoCalculate.tsx
  client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/index.ts
  client/src/pages/MainPage/Section/FeatureSection/CheckDeposit/CheckDeposit.style.ts
  client/src/pages/MainPage/Section/FeatureSection/CheckDeposit/CheckDeposit.tsx
  client/src/pages/MainPage/Section/FeatureSection/CheckDeposit/index.ts
  client/src/pages/MainPage/Section/FeatureSection/FeatureSection.tsx
  client/src/pages/MainPage/Section/FeatureSection/RecordMemoryWithPhoto/RecordMemoryWithPhoto.style.ts
  client/src/pages/MainPage/Section/FeatureSection/RecordMemoryWithPhoto/RecordMemoryWithPhoto.tsx
  client/src/pages/MainPage/Section/FeatureSection/RecordMemoryWithPhoto/index.ts
  client/src/pages/MainPage/Section/FeatureSection/SimpleShare/SimpleShare.style.ts
  client/src/pages/MainPage/Section/FeatureSection/SimpleShare/SimpleShare.tsx
  client/src/pages/MainPage/Section/FeatureSection/SimpleShare/index.ts
  client/src/pages/MainPage/Section/FeatureSection/SimpleTransfer/SimpleTransfer.style.ts
  client/src/pages/MainPage/Section/FeatureSection/SimpleTransfer/SimpleTransfer.tsx
  client/src/pages/MainPage/Section/FeatureSection/SimpleTransfer/index.ts
  client/src/pages/MainPage/Section/FeatureSection/index.ts
  client/src/pages/MainPage/Section/MainSection.tsx
  client/src/pages/MainPage/Section/MainSection/MainSection.style.ts
  client/src/pages/MainPage/Section/MainSection/MainSection.tsx
  client/src/pages/MainPage/Section/MainSection/index.ts
  client/src/pages/MainPage/Section/ReportSection.tsx
Labels: 🖥️ FE

#772 [FE] 문의하기 페이지 구현
  client/src/components/Design/components/Carousel/Carousel.stories.tsx
  client/src/components/Design/components/Carousel/CarouselDeleteButton.tsx
  client/src/components/Design/components/Carousel/CarouselIndicator.tsx
  client/src/components/Design/components/Carousel/useCarousel.ts
  client/src/components/Footer/Footer.tsx
Labels: 🖥️ FE, ⚙️ feat

#771 [FE] 성능 개선 : Preconnect to requered origins
  client/.storybook/preview.tsx
  client/index.html
  client/src/GlobalStyle.ts
  client/src/components/Design/theme/GlobalStyle.ts
Labels: 🖥️ FE, 🚧 refactor

#774 [FE] 성능 개선 : 랜딩 페이지 이미지를 필요한 만큼만 불러오기
  client/src/hooks/useImageLazyLoading.ts
  client/src/pages/MainPage/Section/DescriptionSection/DescriptionSection.tsx
  client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/AutoCalculate.tsx
  client/src/pages/MainPage/Section/FeatureSection/CheckDeposit/CheckDeposit.tsx
  client/src/pages/MainPage/Section/FeatureSection/FeatureSection.tsx
  client/src/pages/MainPage/Section/FeatureSection/RecordMemoryWithPhoto/RecordMemoryWithPhoto.tsx
  client/src/pages/MainPage/Section/FeatureSection/SimpleShare/SimpleShare.tsx
  client/src/pages/MainPage/Section/FeatureSection/SimpleTransfer/SimpleTransfer.tsx
Labels: 🖥️ FE, 🚧 refactor

#776 [FE] 성능 개선 : Kakao script를 필요한 곳에서 다운로드 받기
  client/index.html
  client/src/App.tsx
  client/src/components/Design/components/Dropdown/ButtonBase.tsx
  client/src/components/Design/components/Dropdown/Dropdown.tsx
  client/src/components/Design/components/Dropdown/Dropdown.type.ts
  client/src/components/KakaoInitializer/KakaoInitializer.tsx
  client/src/components/ShareEventButton/MobileShareEventButton.tsx
  client/src/utils/initKakao.ts
Labels: 🖥️ FE, 🚧 refactor

#777 [FE] v2.1.1에서 구현한 랜딩페이지 개선
  client/src/GlobalStyle.ts
  client/src/hooks/useMainPageYScroll.ts
  client/src/hooks/useMainSectionBackgroundScroll.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/Section/CreatorSection.tsx
  client/src/pages/MainPage/Section/CreatorSection/Avatar.style.ts
  client/src/pages/MainPage/Section/CreatorSection/Avatar.tsx
  client/src/pages/MainPage/Section/CreatorSection/CreatorSection.style.ts
  client/src/pages/MainPage/Section/CreatorSection/CreatorSection.tsx
  client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/AutoCalculate.style.ts
  client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/AutoCalculate.tsx
  client/src/pages/MainPage/Section/FeatureSection/CheckDeposit/CheckDeposit.style.ts
  client/src/pages/MainPage/Section/FeatureSection/CheckDeposit/CheckDeposit.tsx
  client/src/pages/MainPage/Section/FeatureSection/FeatureSection.tsx
  client/src/pages/MainPage/Section/FeatureSection/RecordMemoryWithPhoto/RecordMemoryWithPhoto.style.ts
  client/src/pages/MainPage/Section/FeatureSection/RecordMemoryWithPhoto/RecordMemoryWithPhoto.tsx
  client/src/pages/MainPage/Section/FeatureSection/SimpleShare/SimpleShare.style.ts
  client/src/pages/MainPage/Section/FeatureSection/SimpleShare/SimpleShare.tsx
  client/src/pages/MainPage/Section/FeatureSection/SimpleTransfer/SimpleTransfer.style.ts
  client/src/pages/MainPage/Section/FeatureSection/SimpleTransfer/SimpleTransfer.tsx
  client/src/pages/MainPage/Section/MainSection/MainSection.style.ts
  client/src/pages/MainPage/Section/MainSection/MainSection.tsx
Labels: 🖥️ FE, ⚙️ feat

#781 [FE] 홈에서 이벤트 토큰이 있을 때 지출 내역이 수정되는 버그 해결
  client/src/components/StepList/Step.tsx
  client/src/pages/EventPage/HomePage/HomePage.tsx
Labels: 🖥️ FE, 🚨 bug, 🔍 QC, High

#784 [FE] 성능 개선 : Serve images in next-gen formats
  client/src/assets/image/Toss_Symbol_Primary.png
  client/src/assets/image/banksprite.png
  client/src/components/Design/components/BankSelect/BankSelect.style.ts
  client/src/components/Design/components/Icon/Icon.style.ts
  client/src/components/Design/components/Icon/Icon.tsx
  client/src/components/Design/components/Image/Image.tsx
  client/src/components/Logo/Logo.style.ts
  client/src/components/Logo/RunningDogLogo.tsx
  client/src/components/Logo/StandingDogLogo.tsx
  client/src/global.d.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/Section/CreatorSection/Avatar.tsx
  client/src/pages/MainPage/Section/CreatorSection/CreatorSection.tsx
  client/src/pages/MainPage/Section/DescriptionSection/DescriptionSection.tsx
  client/src/pages/MainPage/Section/FeatureSection/RecordMemoryWithPhoto/RecordMemoryWithPhoto.style.ts
  client/src/pages/MainPage/Section/FeatureSection/RecordMemoryWithPhoto/RecordMemoryWithPhoto.tsx
  client/src/pages/MainPage/Section/FeatureSection/SimpleShare/SimpleShare.style.ts
  client/src/pages/MainPage/Section/FeatureSection/SimpleShare/SimpleShare.tsx
  client/src/pages/MainPage/Section/MainSection/MainSection.tsx
  client/src/utils/getImageUrl.ts
Labels: 🖥️ FE, 🚧 refactor

#783 [FE] QR코드로 초대하기 기능 추가
  client/package-lock.json
  client/package.json
  client/src/components/Design/token/zIndex.ts
  client/src/components/ShareEventButton/DesktopShareEventButton.tsx
  client/src/components/ShareEventButton/MobileShareEventButton.tsx
  client/src/constants/routerUrls.ts
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/pages/QRCodePage/QRCodePage.style.ts
  client/src/pages/QRCodePage/QRCodePage.tsx
  client/src/router.tsx
Labels: 🖥️ FE, ⚙️ feat

#790 [BE] tomcat max-thread 변경
  server/src/main/resources/application.yml
Labels: ⌨️ BE, ⚙️ feat

#800 [ALL] infra 구성도 및 CI/CD 파이프라인 추가
  README.md
Labels: 🖥️ FE, ⌨️ BE

#803 [FE] favicon.ico 404 오류 해결
  client/index.html
  client/public/favicon.ico
  client/webpack.common.mjs
Labels: 🖥️ FE, 🚨 bug

#801 [FE] carousel 에 maxWidth가 적용되지 않아 768 이상 해상도에서 짤리는 문제
  client/src/components/Design/components/Carousel/Carousel.style.ts
Labels: 🖥️ FE, ⚙️ feat

#797 [FE] 랜딩페이지 스크롤 오류 해결
  client/src/hooks/useMainPageYScroll.ts
  client/src/hooks/useMainSectionBackgroundScroll.ts
  client/src/pages/MainPage/MainPage.style.ts
  client/src/pages/MainPage/Section/CreatorSection/Avatar.tsx
  client/src/pages/MainPage/Section/CreatorSection/CreatorSection.style.ts
  client/src/pages/MainPage/Section/FeatureSection/FeatureSection.tsx
Labels: 🖥️ FE, ⚙️ feat

#802 [FE] 상세 지출 수정에서 가상 키보드가 선택 영역을 가리는 문제 해결
  client/src/components/Design/components/NumberKeyboard/NumberKeyboardBottomSheet.tsx
  client/src/components/Design/components/NumberKeyboard/useNumberKeyboardBottomSheet.ts
  client/src/hooks/useEditBillKeyboardAction.ts
  client/src/hooks/useEditBillPage.ts
  client/src/hooks/useEditBillPageScroll.ts
  client/src/pages/EditBillPage/EditBillPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#787 [FE] 성능 개선 : bundle main.js 용량 줄이기
  client/package.json
  client/src/App.tsx
  client/src/EssentialQueryApp.tsx
  client/src/router.tsx
  client/webpack.prod.mjs
Labels: 🖥️ FE, 🚧 refactor

#795 [FE] Creator Image Lazy loading 적용
  client/src/hooks/useImageLazyLoading.ts
  client/src/pages/MainPage/Section/CreatorSection/Avatar.tsx
  client/src/pages/MainPage/Section/DescriptionSection/DescriptionSection.tsx
  client/src/pages/MainPage/Section/FeatureSection/AutoCalculate/AutoCalculate.tsx
  client/src/pages/MainPage/Section/FeatureSection/CheckDeposit/CheckDeposit.tsx
  client/src/pages/MainPage/Section/FeatureSection/FeatureSection.tsx
  client/src/pages/MainPage/Section/FeatureSection/RecordMemoryWithPhoto/RecordMemoryWithPhoto.tsx
  client/src/pages/MainPage/Section/FeatureSection/SimpleShare/SimpleShare.tsx
  client/src/pages/MainPage/Section/FeatureSection/SimpleTransfer/SimpleTransfer.tsx
Labels: 🖥️ FE, 🚧 refactor

#806 [FE] 폰트를 프리로드 하도록 수정
  client/index.html
Labels: 🖥️ FE, 🚧 refactor

#808 [FE] 768 이상의 해상도에서 랜딩페이지 좌우 패딩 오류
  client/src/GlobalStyle.ts
  client/src/hooks/useMainSection.ts
  client/src/hooks/useMainSectionBackgroundScroll.ts
  client/src/hooks/usePageBackground.ts
  client/src/pages/MainPage/MainPage.style.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/Section/MainSection/MainSection.tsx
Labels: 🖥️ FE, 🚨 bug, 🔍 QC

#809 [FE] 에러 페이지 구현
  client/src/components/AppErrorBoundary/ErrorCatcher.test.tsx
  client/src/pages/ErrorPage/ErrorPage.tsx
Labels: 🖥️ FE, ⚙️ feat
