Repository woowacourse-teams/2024-haeng-dong, pull requests merged in 2024-08, with the labels that each got.

#161 [BE] 예외메시지 구체화
  server/src/main/java/server/haengdong/application/MemberActionFactory.java
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/domain/action/CurrentMembers.java
  server/src/main/java/server/haengdong/exception/ErrorResponse.java
  server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/main/java/server/haengdong/exception/HaengdongException.java
  server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java
  server/src/test/java/server/haengdong/domain/action/CurrentMembersTest.java
Labels: ⌨️ BE, ⚙️ feat

#166 [FE] 토스트 생성
  HDesign/package-lock.json
  HDesign/src/assets/confirm.svg
  HDesign/src/assets/error.svg
  HDesign/src/components/Button/Button.style.ts
  HDesign/src/components/Toast/Toast.stories.tsx
  HDesign/src/components/Toast/Toast.style.ts
  HDesign/src/components/Toast/Toast.tsx
  HDesign/src/components/Toast/Toast.type.ts
  HDesign/src/components/Toast/ToastProvider.stories.tsx
  HDesign/src/components/Toast/ToastProvider.tsx
  HDesign/src/components/Toast/useToast.ts
  HDesign/src/index.tsx
Labels: 🖥️ FE, ⚙️ feat

#173 [FE] client 디렉토리 reset, 전역 스타일 GlobalStyle을 사용하는 것으로 변경
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/GlobalStyle.ts
  client/src/index.css
  client/src/index.tsx
  client/src/reset.css
  client/webpack.config.js
Labels: 🖥️ FE, 🚧 refactor

#171 [FE] Button컴포넌트에서 disabled일 때 커서 포인터가 보임
  HDesign/src/theme/GlobalStyle.ts
Labels: 🖥️ FE, 🚨 bug

#141 [BE] 액션 이력 조회 리펙토링
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/java/server/haengdong/presentation/response/ActionsResponse.java
  server/src/main/java/server/haengdong/presentation/response/StepResponse.java
  server/src/main/java/server/haengdong/presentation/response/StepsResponse.java
  server/src/test/java/server/haengdong/presentation/response/StepResponseTest.java
  server/src/test/java/server/haengdong/presentation/response/StepsResponseTest.java
Labels: ⌨️ BE, 🚧 refactor

#181 [BE] 멤버 액션 삭제 기능 구현
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/domain/action/ActionRepository.java
  server/src/main/java/server/haengdong/domain/action/BillActionRepository.java
  server/src/main/java/server/haengdong/domain/action/MemberActionRepository.java
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/main/java/server/haengdong/presentation/MemberActionController.java
  server/src/test/java/server/haengdong/application/ActionServiceTest.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
  server/src/test/java/server/haengdong/presentation/MemberActionControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#190 [BE] ERD svg 생성하여 스키마 변경에 대한 이력 관리
  server/docs/24-08-04-erd.sql
  server/docs/24-08-04-erd.svg
Labels: ⌨️ BE, ⚙️ feat

#180 [BE] 지출 액션 수정 기능 구현
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/application/request/BillActionUpdateAppRequest.java
  server/src/main/java/server/haengdong/domain/action/BillAction.java
  server/src/main/java/server/haengdong/domain/action/BillActionRepository.java
  server/src/main/java/server/haengdong/domain/event/Event.java
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/main/java/server/haengdong/presentation/BillActionController.java
  server/src/main/java/server/haengdong/presentation/request/BillActionUpdateRequest.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/presentation/BillActionControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#179 [BE] 지출 액션 삭제 기능 구현
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/domain/action/BillAction.java
  server/src/main/java/server/haengdong/domain/action/BillActionRepository.java
  server/src/main/java/server/haengdong/domain/event/EventRepository.java
  server/src/main/java/server/haengdong/presentation/BillActionController.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/presentation/BillActionControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#185 [BE] 행사의 전체 참여자 중 특정 참여자의 멤버 액션을 모두 삭제하는 기능 구현
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/domain/action/MemberActionRepository.java
  server/src/main/java/server/haengdong/presentation/MemberActionController.java
  server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
  server/src/test/java/server/haengdong/presentation/MemberActionControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#195 [BE] 행사에 참여한 전체 인원 조회 기능 구현
  .github/workflows/backend-dev.yml
  .github/workflows/backend-pull-request.yml
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/application/response/MembersAppResponse.java
  server/src/main/java/server/haengdong/domain/action/MemberActionRepository.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/java/server/haengdong/presentation/response/MembersResponse.java
  server/src/test/java/server/haengdong/application/EventServiceTest.java
  server/src/test/java/server/haengdong/presentation/EventControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#199 [BE] 테스트 데이터 클리너 구현
  server/src/test/java/server/haengdong/application/ActionServiceTest.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/application/EventServiceTest.java
  server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java
  server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
  server/src/test/java/server/haengdong/support/extension/DatabaseCleaner.java
  server/src/test/java/server/haengdong/support/extension/DatabaseCleanerExtension.java
Labels: ⌨️ BE, ⚙️ feat

#198 [FE] 디자인시스템 hover, mouse, transition animation
  .github/workflows/design-pull-request.yml
  HDesign/.storybook/main.ts
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/BillItem/BillItem.style.ts
  HDesign/src/components/BottomSheet/BottomSheet.stories.tsx
  HDesign/src/components/BottomSheet/BottomSheet.style.ts
  HDesign/src/components/BottomSheet/BottomSheet.tsx
  HDesign/src/components/BottomSheet/BottomSheet.type.ts
  HDesign/src/components/BottomSheet/useBottomSheet.ts
  HDesign/src/components/Button/Button.style.ts
  HDesign/src/components/DragHandleItem/DragHandleItem.style.ts
  HDesign/src/components/DragHandleItem/DragHandleItem.tsx
  HDesign/src/components/ExpenseList/ExpenseList.style.ts
  HDesign/src/components/FixedButton/FixedButton.style.ts
  HDesign/src/components/Flex/Flex.style.ts
  HDesign/src/components/Flex/Flex.tsx
  HDesign/src/components/Flex/Flex.type.ts
  HDesign/src/components/IconButton/IconButton.tsx
  HDesign/src/components/InOutItem/InOutItem.style.ts
  HDesign/src/components/Input/Input.stories.tsx
  HDesign/src/components/Input/Input.style.ts
  HDesign/src/components/Input/Input.tsx
  HDesign/src/components/Input/useInput.ts
  HDesign/src/components/LabelGroupInput/Element.tsx
  HDesign/src/components/LabelGroupInput/GroupInputContext.tsx
  HDesign/src/components/LabelGroupInput/LabelGroupInput.stories.tsx
  HDesign/src/components/LabelGroupInput/LabelGroupInput.style.ts
  HDesign/src/components/LabelGroupInput/LabelGroupInput.tsx
  HDesign/src/components/LabelInput/LabelInput.stories.tsx
  HDesign/src/components/LabelInput/LabelInput.style.ts
  HDesign/src/components/LabelInput/LabelInput.tsx
  HDesign/src/components/LabelInput/LabelInput.type.ts
  HDesign/src/components/LabelInput/useLabelInput.ts
  HDesign/src/components/Search/Search.style.ts
  HDesign/src/components/StepItem/StepItem.style.ts
  HDesign/src/components/StepItem/StepItem.tsx
  HDesign/src/components/Tabs/Tabs.stories.tsx
  HDesign/src/components/Tabs/Tabs.style.ts
  HDesign/src/components/TextButton/TextButton.style.ts
  HDesign/src/components/TextButton/TextButton.tsx
  HDesign/src/components/Toast/Toast.style.ts
  HDesign/src/index.tsx
  HDesign/src/type/strictPropsWithChildren.ts
  HDesign/src/utils/changeCamelCaseToKebabCase.ts
  HDesign/src/utils/colors.ts
  HDesign/tsconfig.json
Labels: 🖥️ FE, 🚨 bug, 🎨 Design

#203 [FE] ListButton component 생성
  HDesign/.storybook/preview.tsx
  HDesign/src/assets/index.ts
  HDesign/src/assets/rightChevron.svg
  HDesign/src/components/IconButton/IconButton.tsx
  HDesign/src/components/IconButton/IconButton.type.ts
  HDesign/src/components/ListButton/ListButton.stories.tsx
  HDesign/src/components/ListButton/ListButton.style.ts
  HDesign/src/components/ListButton/ListButton.tsx
  HDesign/src/components/ListButton/ListButton.type.ts
Labels: 🖥️ FE, ⚙️ feat, 🎨 Design

#211 [FE] 개별 ActionItem 컨트롤을 위한 StepItem 및 BillItem / InOutItem component 구조 변경
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/assets/arrow.svg
  HDesign/src/assets/buljusa.svg
  HDesign/src/assets/confirm.svg
  HDesign/src/assets/error.svg
  HDesign/src/assets/index.ts
  HDesign/src/assets/inputDelete.svg
  HDesign/src/assets/plus.svg
  HDesign/src/assets/rightChevron.svg
  HDesign/src/assets/search.svg
  HDesign/src/assets/trash.svg
  HDesign/src/components/BillItem/BillItem.stories.tsx
  HDesign/src/components/BillItem/BillItem.style.ts
  HDesign/src/components/BillItem/BillItem.tsx
  HDesign/src/components/BillItem/BillItem.type.ts
  HDesign/src/components/BottomSheet/BottomSheet.tsx
  HDesign/src/components/BottomSheet/BottomSheet.type.ts
  HDesign/src/components/DragHandleItem/DragHandleItem.stories.tsx
  HDesign/src/components/DragHandleItem/DragHandleItem.style.ts
  HDesign/src/components/DragHandleItem/DragHandleItem.tsx
  HDesign/src/components/DragHandleItem/DragHandleItem.type.ts
  HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.stories.tsx
  HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.style.ts
  HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.tsx
  HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.type.ts
  HDesign/src/components/ExpenseList/ExpenseList.tsx
  HDesign/src/components/FixedButton/FixedButton.tsx
  HDesign/src/components/Icon/Icon.stories.tsx
  HDesign/src/components/Icon/Icon.style.ts
  HDesign/src/components/Icon/Icon.tsx
  HDesign/src/components/Icon/Icon.type.ts
  HDesign/src/components/IconButton/IconButton.stories.tsx
  HDesign/src/components/IconButton/IconButton.style.ts
  HDesign/src/components/IconButton/IconButton.tsx
  HDesign/src/components/IconButton/IconButton.type.ts
  HDesign/src/components/InOutItem/InOutItem.stories.tsx
  HDesign/src/components/InOutItem/InOutItem.style.ts
  HDesign/src/components/InOutItem/InOutItem.tsx
  HDesign/src/components/InOutItem/InOutItem.type.ts
  HDesign/src/components/Input/Input.tsx
  HDesign/src/components/ListButton/ListButton.tsx
  HDesign/src/components/StepItem/StepItem.stories.tsx
  HDesign/src/components/StepItem/StepItem.style.ts
  HDesign/src/components/StepItem/StepItem.tsx
  HDesign/src/components/StepItem/StepItem.type.ts
  HDesign/src/components/Toast/Toast.tsx
  HDesign/src/index.tsx
  HDesign/src/token/colors.ts
Labels: 🖥️ FE, ⚙️ feat, 🚧 refactor, 🎨 Design

#209 [FE] 삭제 아이콘을 위한 IconButton component 수정
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/assets/confirm.svg
  HDesign/src/assets/error.svg
  HDesign/src/components/Icon/Icon.style.ts
  HDesign/src/components/Icon/Icon.tsx
  HDesign/src/components/Icon/Icon.type.ts
  HDesign/src/components/IconButton/IconButton.stories.tsx
  HDesign/src/components/IconButton/IconButton.style.ts
  HDesign/src/components/IconButton/IconButton.tsx
  HDesign/src/components/IconButton/IconButton.type.ts
Labels: 🖥️ FE, ⚙️ feat, 🚧 refactor, 🎨 Design

#222 [BE] 로그인 토큰 인증 오류
  server/src/main/java/server/haengdong/config/AdminInterceptor.java
Labels: ⌨️ BE, 🚨 bug

#235 [BE] CORS, 쿠키 인증오류 수정
  server/src/main/java/server/haengdong/config/AdminInterceptor.java
  server/src/main/resources/application.yml
Labels: ⌨️ BE, 🚨 bug

#234 [FE] FixedButton의 delete button type "button"으로 변경
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/FixedButton/FixedButton.tsx
  HDesign/src/components/IconButton/IconButton.style.ts
Labels: 🖥️ FE, 🚨 bug

#226 [FE] 행사생성 flow에서 admin 접근을 위한 비밀번호를 입력받는 기능 추가
  client/src/apis/fetcher.ts
  client/src/apis/request/event.ts
  client/src/apis/requestPostEvent.ts
  client/src/constants/errorMessage.ts
  client/src/constants/regExp.ts
  client/src/constants/routerUrls.ts
  client/src/constants/rule.ts
  client/src/pages/CreateEventPage/SetEventNamePage.tsx
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
  client/src/router.tsx
  client/src/utils/validate/validateEventPassword.ts
  client/webpack.config.js
Labels: 🖥️ FE, ⚙️ feat

#227 [BE] 에러 코드 재정의
  server/src/main/java/server/haengdong/application/ActionService.java
  server/src/main/java/server/haengdong/application/AuthService.java
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/application/MemberActionFactory.java
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/config/AdminInterceptor.java
  server/src/main/java/server/haengdong/domain/action/BillAction.java
  server/src/main/java/server/haengdong/domain/action/CurrentMembers.java
  server/src/main/java/server/haengdong/domain/action/MemberAction.java
  server/src/main/java/server/haengdong/domain/action/MemberActionStatus.java
  server/src/main/java/server/haengdong/domain/event/Event.java
  server/src/main/java/server/haengdong/exception/AuthenticationException.java
  server/src/main/java/server/haengdong/exception/ErrorResponse.java
  server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/main/java/server/haengdong/exception/HaengdongException.java
  server/src/main/java/server/haengdong/infrastructure/auth/AuthenticationExtractor.java
  server/src/main/java/server/haengdong/presentation/request/BillActionSaveRequest.java
  server/src/main/java/server/haengdong/presentation/request/BillActionUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/request/BillActionsSaveRequest.java
  server/src/main/java/server/haengdong/presentation/request/EventLoginRequest.java
  server/src/main/java/server/haengdong/presentation/request/EventSaveRequest.java
  server/src/main/java/server/haengdong/presentation/request/MemberActionsSaveRequest.java
  server/src/main/java/server/haengdong/presentation/request/MemberUpdateRequest.java
  server/src/test/java/server/haengdong/application/ActionServiceTest.java
  server/src/test/java/server/haengdong/domain/action/BillActionTest.java
  server/src/test/java/server/haengdong/domain/event/EventTest.java
  server/src/test/java/server/haengdong/presentation/BillActionControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#237 [BE] 쿠키 저장 오류 2차 수정
  server/src/main/java/server/haengdong/config/WebMvcConfig.java
  server/src/main/java/server/haengdong/infrastructure/auth/CookieProperties.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/resources/application.yml
Labels: ⌨️ BE, 🚨 bug

#228 [FE] 전체 참여자 BottomSheet 내부 디자인 퍼블리싱
  client/src/components/InputAndDeleteButton/InputAndDeleteButton.style.ts
  client/src/components/InputAndDeleteButton/InputAndDeleteButton.tsx
  client/src/components/Modal/ModalBasedOnMemberCount/ModalBasedOnMemberCount.tsx
  client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/AddMemberActionListModalContent.tsx
  client/src/components/Modal/SetActionModal/SetActionListModal.tsx
  client/src/components/Modal/SetAllMemberListModal/SetAllMemberListModal.style.ts
  client/src/components/Modal/SetAllMemberListModal/SetAllMemberListModal.tsx
  client/src/components/Modal/SetInitialMemberListModal/SetInitialMemberListModal.tsx
  client/src/components/Modal/index.ts
  client/src/components/StepList/BillStepItem.tsx
  client/src/components/StepList/MemberStepItem.tsx
  client/src/components/StepList/Step.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.style.ts
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#232 [FE] api에러 등의 에러를 잡아 핸들링
  client/package-lock.json
  client/package.json
  client/public/mockServiceWorker.js
  client/src/App.tsx
  client/src/ErrorProvider.tsx
  client/src/UnhandledErrorBoundary.tsx
  client/src/apis/fetcher.ts
  client/src/apis/request/event.ts
  client/src/apis/useFetch.ts
  client/src/components/Toast/Toast.style.ts
  client/src/components/Toast/Toast.tsx
  client/src/components/Toast/Toast.type.ts
  client/src/components/Toast/ToastProvider.tsx
  client/src/constants/errorMessage.ts
  client/src/hooks/useEvent.tsx
  client/src/index.tsx
  client/src/mocks/browser.ts
  client/src/mocks/handlers.ts
  client/src/pages/CreateEventPage/SetEventNamePage.tsx
  client/src/pages/ErrorPage/ErrorPage.tsx
  client/src/router.tsx
  client/webpack.config.js
Labels: 🖥️ FE, ⚙️ feat

#238 [BE] REST docs를 통한 문서화
  server/build.gradle
  server/src/docs/asciidoc/billAction.adoc
  server/src/docs/asciidoc/event.adoc
  server/src/docs/asciidoc/index.adoc
  server/src/docs/asciidoc/memberAction.adoc
  server/src/docs/asciidoc/memberBillReport.adoc
  server/src/test/java/server/haengdong/docs/ActionControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/BillActionControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/MemberActionControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/RestDocsSupport.java
  server/src/test/java/server/haengdong/support/fixture/Fixture.java
Labels: ⌨️ BE, ⚙️ feat

#217 [FE] 빌드 환경 prod와 dev로 구분
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/webpack.common.mjs
  client/webpack.dev.mjs
  client/webpack.prod.mjs
Labels: 🖥️ FE, ⚙️ feat, 🛠️ Setting

#246 [FE] merge를 통해 발생한 에러 해결
  client/src/apis/fetcher.ts
  client/src/apis/request/event.ts
  client/src/components/StepList/BillStepItem.tsx
  client/src/hooks/useEvent.tsx
  client/src/index.tsx
  client/src/pages/CreateEventPage/SetEventNamePage.tsx
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
Labels: 🖥️ FE, 🚨 bug, 🛠️ Setting, High

#253 [FE] input value 수정이 되지 않는 문제
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/Input/useInput.ts
Labels: 🖥️ FE, 🚨 bug

#259 [BE] 관리자 권한 확인 API 구현
  .github/workflows/backend-pull-request.yml
  server/src/docs/asciidoc/event.adoc
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
Labels: ⌨️ BE, ⚙️ feat

#264 [FE] 멤버 내역을 클릭할 때 에러 바운더리가 실행되는 버그
  client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.tsx
Labels: 🖥️ FE, 🚨 bug

#257 [FE] 디자인시스템 Text 컴포넌트 color prop 받도록 변경
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/DragHandleItem/DragHandleItem.style.ts
  HDesign/src/components/DragHandleItem/DragHandleItem.tsx
  HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.style.ts
  HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.tsx
  HDesign/src/components/ExpenseList/ExpenseList.style.ts
  HDesign/src/components/ExpenseList/ExpenseList.tsx
  HDesign/src/components/ListButton/ListButton.style.ts
  HDesign/src/components/ListButton/ListButton.tsx
  HDesign/src/components/Text/Text.style.ts
  HDesign/src/components/Text/Text.tsx
  HDesign/src/components/Text/Text.type.ts
  HDesign/src/components/TextButton/TextButton.style.ts
  HDesign/src/components/TextButton/TextButton.tsx
  HDesign/src/components/Title/Title.style.ts
  HDesign/src/components/Title/Title.tsx
Labels: 🖥️ FE, 🚧 refactor, 🎨 Design

#265 [BE] 참여자 삭제 메서드 @Transactional 추가
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/resources/application.yml
Labels: ⌨️ BE, 🚨 bug

#266 [FE] 디자인시스템 Input value 동기화 오류 수정
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/Input/Input.stories.tsx
  HDesign/src/components/Input/Input.tsx
  HDesign/src/components/Input/useInput.ts
Labels: 🖥️ FE, 🚨 bug, 🎨 Design

#260 [FE] 행동디자인 Search 컴포넌트 기능 제거
  HDesign/src/components/Search/Search.stories.tsx
  HDesign/src/components/Search/Search.style.ts
  HDesign/src/components/Search/Search.tsx
  HDesign/src/components/Search/useSearch.ts
Labels: 🖥️ FE, ⚙️ feat

#271 [FE] 행사 생성 완료 페이지 유저 친화적으로 변경
  client/package-lock.json
  client/package.json
  client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#270 [FE] 인원 탈주 시 인원 검색 기능 구현
  client/package.json
  client/src/apis/request/member.ts
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/AddMemberActionListModalContent.style.ts
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/AddMemberActionListModalContent.tsx
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/InMember.tsx
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/OutMember.tsx
  client/src/hooks/useDynamicInput.tsx
  client/src/hooks/useSearchInMemberList.ts
Labels: 🖥️ FE, ⚙️ feat

#250 [FE] 전체 참여자 데이터 요청하고 출력하기
  client/src/apis/request/member.ts
  client/src/components/InputAndDeleteButton/InputAndDeleteButton.tsx
  client/src/components/Modal/ModalBasedOnMemberCount/ModalBasedOnMemberCount.tsx
  client/src/components/Modal/SetAllMemberListModal/SetAllMemberListModal.tsx
  client/src/components/Modal/index.ts
  client/src/hooks/useStepList/useStepList.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#276 [FE] 전체 참여자 이름 수정 및 삭제
  client/src/apis/fetcher.ts
  client/src/apis/request/member.ts
  client/src/components/InputAndDeleteButton/InputAndDeleteButton.style.ts
  client/src/components/InputAndDeleteButton/InputAndDeleteButton.tsx
  client/src/components/Modal/SetAllMemberListModal/SetAllMemberListModal.style.ts
  client/src/components/Modal/SetAllMemberListModal/SetAllMemberListModal.tsx
  client/src/components/Toast/ToastProvider.tsx
  client/src/constants/rule.ts
  client/src/hooks/useSetAllMemberList.tsx
  client/src/utils/validate/validateMemberName.ts
Labels: 🖥️ FE, ⚙️ feat

#262 [FE] sentry 적용
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/mockServiceWorker.js
  client/src/ErrorProvider.tsx
  client/src/apis/fetcher.ts
  client/src/apis/useFetch.ts
  client/src/constants/errorMessage.ts
  client/src/errors/FetchError.ts
  client/src/hooks/useStepList/useStepList.tsx
  client/src/index.tsx
  client/src/types/fetchErrorType.ts
  client/src/utils/sendLogToSentry.ts
  client/tsconfig.json
  client/webpack.common.mjs
  client/webpack.dev.mjs
  client/webpack.prod.mjs
Labels: 🖥️ FE, 🛠️ Setting

#280 [FE] 3차 데모데이 merge 중 발생한 문제 수정
  HDesign/package-lock.json
  HDesign/package.json
  client/package-lock.json
  client/package.json
  client/src/apis/fetcher.ts
  client/src/apis/request/auth.ts
  client/src/apis/request/member.ts
  client/src/components/Modal/SetAllMemberListModal/SetAllMemberListModal.tsx
  client/src/hooks/useAuth.tsx
  client/src/index.tsx
  client/src/pages/EventPage/AdminPage/EventLoginPage.tsx
  client/src/utils/sendLogToSentry.ts
Labels: 🖥️ FE, 🚨 bug, High

#285 [FE] 홈에서 액션 수정 삭제 바텀시트 활성화 버그
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/OutMember.tsx
  client/src/components/StepList/BillStepItem.tsx
  client/src/components/StepList/MemberStepItem.tsx
  client/src/components/StepList/StepList.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
Labels: 🖥️ FE, 🚨 bug

#286 [FE] cookie가 없는 경우 비밀번호 입력 페이지로 이동
  client/src/apis/request/auth.ts
  client/src/apis/useFetch.ts
  client/src/constants/routerUrls.ts
  client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/EventPage/AdminPage/EventLoginPage.tsx
  client/src/router.tsx
  client/webpack.dev.mjs
Labels: 🖥️ FE, ⚙️ feat

#269 [BE] actuator metrics 추가하여 모니터링 대상 확장
  server/src/main/resources/application.yml
Labels: ⌨️ BE, 🚧 refactor

#290 Hoxfix/#08091022
  server/src/main/java/server/haengdong/HaengdongApplication.java
Labels: ⌨️ BE, ⚙️ feat

#293 [FE] webpack.dev.mjs에 sentryWebpackPlugin가 import되어있지 않음
  client/webpack.dev.mjs
Labels: 🖥️ FE, 🚨 bug

#268 [BE] 행사 참여 인원 이름 변경 api 수정
  server/src/docs/asciidoc/event.adoc
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/application/request/MemberNameUpdateAppRequest.java
  server/src/main/java/server/haengdong/application/request/MemberNamesUpdateAppRequest.java
  server/src/main/java/server/haengdong/application/request/MemberUpdateAppRequest.java
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/java/server/haengdong/presentation/request/MemberNameUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/request/MemberNamesUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/request/MemberUpdateRequest.java
  server/src/test/java/server/haengdong/application/EventServiceTest.java
  server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
  server/src/test/java/server/haengdong/presentation/EventControllerTest.java
Labels: ⌨️ BE, ⚙️ feat

#273 [BE] REST docs가 배포되지 않는 버그 수정
  server/build.gradle
Labels: ⌨️ BE, 🚨 bug

#283 [BE] 행사 로그인 버그 수정
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/config/AdminInterceptor.java
  server/src/main/java/server/haengdong/domain/event/Event.java
Labels: ⌨️ BE, 🚨 bug

#308 [BE] CI/CD 트리거 조건에서 server 폴더 조건 제거
  .github/workflows/backend-dev.yml
  .github/workflows/backend-pull-request.yml
Labels: ⌨️ BE, 🚨 bug

#309 [ALL] pr 머지시 issue close 기능 추가
  .github/workflows/pr-issue-close.yml
Labels: 🖥️ FE, ⌨️ BE, ⚙️ feat

#305 [BE] yml, Dockerfile TZ Asia/Seoul 적용
  server/Dockerfile
  server/src/main/resources/application.yml
Labels: ⌨️ BE, 🚧 refactor

#315 [FE] 전체 참여자 수정 및 삭제 수정
  client/src/hooks/useSetAllMemberList.tsx
  client/src/utils/isArraysEqual.ts
Labels: 🖥️ FE, ⚙️ feat, 🚧 refactor

#311 [FE] 3차 스프린트 이후 Todo 기능 구현 (by 쿠키)
  HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.stories.tsx
  HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.style.ts
  HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.tsx
  HDesign/src/components/DragHandleItemContainer/DragHandleItemContainer.type.ts
  client/src/apis/useFetch.ts
  client/src/components/Modal/MemberListInBillStep/MemberListInBillStep.style.ts
  client/src/components/Modal/MemberListInBillStep/MemberListInBillStep.tsx
  client/src/components/Modal/MemberListInBillStep/index.ts
  client/src/components/Modal/ModalBasedOnMemberCount/ModalBasedOnMemberCount.tsx
  client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx
  client/src/components/Modal/SetActionModal/DeleteMemberActionModal/DeleteMemberActionModal.tsx
  client/src/components/Modal/SetActionModal/SetActionListModal.tsx
  client/src/components/StepList/BillStepItem.tsx
  client/src/components/StepList/MemberStepItem.tsx
  client/src/hooks/useAuth.tsx
  client/src/hooks/useDeleteMemberAction.tsx
  client/src/hooks/useEvent.tsx
  client/src/hooks/usePutAndDeleteBillAction.ts
  client/src/hooks/useSearchInMemberList.ts
  client/src/hooks/useSearchMemberReportList.tsx
  client/src/hooks/useSetAllMemberList.tsx
  client/src/hooks/useStepList.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
Labels: 🖥️ FE, ⚙️ feat

#303 [BE] actuator health 엔드포인트 설정 변경
  server/src/main/java/server/haengdong/HaengdongApplication.java
  server/src/main/java/server/haengdong/config/AdminInterceptor.java
  server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/resources/application.yml
  server/src/main/resources/logback-spring.xml
Labels: ⌨️ BE, ⚙️ feat

#318 [FE] 참여 인원 확인 임시 버튼 삭제
  client/package-lock.json
  client/package.json
  client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx
  client/src/components/StepList/BillStepItem.tsx
Labels: 🖥️ FE, ⚙️ feat

#300 [BE] 서버 로그 볼륨 마운트 설정
  .github/workflows/backend-dev.yml
  .github/workflows/backend-prod.yml
Labels: ⌨️ BE, ⚙️ feat

#321 [FE] BottomSheet component width 수정
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/BottomSheet/BottomSheet.style.ts
Labels: 🖥️ FE, 🎨 Design

#324 [FE] 메인, 관리 페이지 설명글 수정
  client/src/assets/image/dog.svg
  client/src/components/Common/Logo/Logo.style.ts
  client/src/components/Common/Logo/Logo.tsx
  client/src/components/Common/Logo/index.ts
  client/src/global.d.ts
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#327 [FE] useDynamicInput 버그 수정
  client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/InMember.tsx
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/OutMember.tsx
  client/src/components/Modal/SetInitialMemberListModal/SetInitialMemberListModal.tsx
  client/src/constants/errorMessage.ts
  client/src/hooks/useDynamicBillActionInput.tsx
  client/src/hooks/useDynamicInput.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/utils/sendLogToSentry.ts
Labels: 🖥️ FE, ⚙️ feat, 🚨 bug

#329 [FE] 홈 및 관리 페이지에서 링크 복사 기능 추가
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/TopNav/TopNav.style.ts
  client/package-lock.json
  client/package.json
  client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/pages/EventPage/HomePage/HomePage.tsx
Labels: 🖥️ FE, ⚙️ feat, 🚧 refactor

#334 [BE] 로그백 설정 오타 수정
  server/src/main/resources/logback-spring.xml
Labels: ⌨️ BE, 🚨 bug

#328 [ALL] pr issue close workflow 생성
  .github/workflows/pr-issue-close.yml
Labels: 🖥️ FE, ⚙️ feat

#331 [FE] cypress 적용 및 행사 생성 flow e2e 테스트 작성
  .github/workflows/frontend-pull-request.yml
  client/cypress.config.ts
  client/cypress/constants/constants.ts
  client/cypress/e2e/createEvent.cy.ts
  client/cypress/fixtures/postEvent.json
  client/cypress/support/commands.ts
  client/cypress/support/e2e.ts
  client/package-lock.json
  client/package.json
  client/tsconfig.json
  client/webpack.dev.mjs
Labels: 🖥️ FE, ⚙️ feat, 🛠️ Setting

#338 [FE] 토큰이 없을 때, 관리페이지로 이동하면 오류가 발생하는 부분 수정
  client/src/apis/useFetch.ts
  client/src/constants/regExp.ts
  client/src/hooks/useDeleteMemberAction.tsx
  client/src/hooks/useEventId.tsx
  client/src/hooks/usePutAndDeleteBillAction.ts
  client/src/hooks/useSearchInMemberList.ts
  client/src/hooks/useSearchMemberReportList.tsx
  client/src/hooks/useSetAllMemberList.tsx
  client/src/hooks/useStepList.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/EventPage/AdminPage/EventLoginPage.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/utils/getEventIdByUrl.ts
Labels: 🖥️ FE, 🚨 bug

#339 [FE] 인원 탈주 추가 시 disable 버그
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/OutMember.tsx
  client/src/hooks/useDynamicInput.tsx
  client/src/hooks/useSearchInMemberList.ts
Labels: 🖥️ FE, 🚨 bug, High

#361 [BE] 현재 행사에 참여 중인 참여자 목록 조회 API 응답 형식 수정
  server/src/main/java/server/haengdong/presentation/response/CurrentMemberResponse.java
  server/src/main/java/server/haengdong/presentation/response/CurrentMembersResponse.java
  server/src/test/java/server/haengdong/docs/MemberActionControllerDocsTest.java
  server/src/test/java/server/haengdong/presentation/MemberActionControllerTest.java
Labels: ⌨️ BE, 🚧 refactor

#363 [BE] BillActionDetail 엔티티 추가
  server/src/main/java/server/haengdong/application/BillActionDetailService.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetail.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetailRepository.java
  server/src/main/java/server/haengdong/presentation/BillActionDetailController.java
Labels: ⌨️ BE, ⚙️ feat

#343 [FE] Sentry prod 환경에서만 돌아가도록 fetcher 설정
  client/src/apis/useFetch.ts
  client/src/global.d.ts
Labels: 🖥️ FE, 🛠️ Setting

#345 [FE] 환경 변수 타입 선언
  client/src/apis/baseUrl.ts
  client/src/global.d.ts
  client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/utils/getEventPageUrlByEnvironment.ts
Labels: 🖥️ FE, 🚧 refactor

#347 [FE] useDeleteMemberAction 토스트 함수 결합도 제거
  client/src/components/Modal/SetActionModal/DeleteMemberActionModal/DeleteMemberActionModal.tsx
  client/src/hooks/useDeleteMemberAction.tsx
Labels: 🖥️ FE, 🚧 refactor

#352 [FE] 사용성 개선 - Title component 변경 및 UX writing 수정
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/Text/Text.style.ts
  HDesign/src/components/Title/Title.stories.tsx
  HDesign/src/components/Title/Title.tsx
  client/package-lock.json
  client/package.json
  client/src/components/Modal/SetInitialMemberListModal/SetInitialMemberListModal.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
Labels: 🖥️ FE, ⚙️ feat, 🔍 QC, 🎨 Design

#354 [FE] 비밀번호 입력 페이지 커스텀 훅으로 분리
  client/src/hooks/useSetPassword.ts
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
  client/src/pages/CreateEventPage/index.ts
  client/src/router.tsx
Labels: 🖥️ FE, 🚧 refactor

#356 [FE] 탭 클릭 시 탭 전체가 클릭 되는 현상
  HDesign/src/components/Tabs/Tabs.style.ts
Labels: 🖥️ FE, 🚨 bug

#357 [FE] 사용성 개선 - 지출 내역 입력 아이템 구현
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/EditableItem/EditableItem.Input.style.ts
  HDesign/src/components/EditableItem/EditableItem.Input.tsx
  HDesign/src/components/EditableItem/EditableItem.Input.type.ts
  HDesign/src/components/EditableItem/EditableItem.context.tsx
  HDesign/src/components/EditableItem/EditableItem.input.stories.tsx
  HDesign/src/components/EditableItem/EditableItem.stories.tsx
  HDesign/src/components/EditableItem/EditableItem.style.ts
  HDesign/src/components/EditableItem/EditableItem.tsx
  HDesign/src/components/EditableItem/EditableItem.type.ts
  HDesign/src/components/EditableItem/useEditableItem.ts
  HDesign/src/components/EditableItem/useEditableItemInput.ts
  HDesign/src/index.tsx
Labels: 🖥️ FE, ⚙️ feat, 🎨 Design

#350 [FE] 행사 생성 완료 페이지에서 불필요한 상태 제거
  client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
  client/src/pages/CreateEventPage/SetEventNamePage.tsx
Labels: 🖥️ FE, 🚧 refactor

#375 [BE]  액션 이력 조회 v2 기능 구현
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/java/server/haengdong/presentation/response/ActionResponse2.java
  server/src/main/java/server/haengdong/presentation/response/ActionsResponse.java
  server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
Labels: ⌨️ BE, ⚙️ feat

#368 [FE] 인원 탈주 검색이 되지 않는 버그
  client/src/apis/request/member.ts
  client/src/hooks/useSearchInMemberList.ts
Labels: 🖥️ FE, 🚨 bug

#370 [BE] 행사 참여 인원 또는 지출 총액 변동시 차등 정산 초기화 기능 구현
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetail.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetailRepository.java
  server/src/main/java/server/haengdong/domain/action/BillActionRepository.java
  server/src/main/java/server/haengdong/domain/action/CurrentMembers.java
  server/src/main/java/server/haengdong/domain/action/MemberActionRepository.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
Labels: ⌨️ BE, ⚙️ feat

#381 [FE] 행사 생성 완료 페이지 머지하면서 잘못된 코드 수정
  client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
Labels: 🖥️ FE, 🚨 bug

#376 [FE] Input 검증 에러 메시지 타입 구조 변경
  HDesign/src/components/LabelGroupInput/LabelGroupInput.type.ts
  HDesign/src/components/LabelInput/LabelInput.tsx
  HDesign/src/components/LabelInput/LabelInput.type.ts
  client/src/ErrorProvider.tsx
  client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx
  client/src/components/Toast/ToastProvider.tsx
  client/src/constants/errorMessage.ts
  client/src/hooks/useDynamicBillActionInput.tsx
  client/src/hooks/useDynamicInput.tsx
  client/src/hooks/usePutAndDeleteBillAction.ts
  client/src/hooks/useSetPassword.ts
  client/src/utils/validate/type.ts
  client/src/utils/validate/validateEventName.ts
  client/src/utils/validate/validateEventPassword.ts
  client/src/utils/validate/validateMemberName.ts
  client/src/utils/validate/validatePurchase.ts
Labels: 🖥️ FE, 🚧 refactor

#379 [FE] 공통 input 코드를 useInput hook으로 분리
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/OutMember.tsx
  client/src/constants/errorMessage.ts
  client/src/hooks/useDynamicInput.tsx
  client/src/hooks/useInput.tsx
  client/src/hooks/useSearchInMemberList.ts
  client/src/hooks/useSetAllMemberList.tsx
  client/src/utils/isArraysEqual.ts
  client/src/utils/validate/validateMemberName.ts
Labels: 🖥️ FE, ⚙️ feat

#358 [FE] 훅에 필요한 테스트 추가
  .github/workflows/frontend-pull-request.yml
  client/jest.config.ts
  client/jest.polyfills.ts
  client/jest.setup.ts
  client/package-lock.json
  client/package.json
  client/src/ErrorProvider.tsx
  client/src/apis/fetcher.ts
  client/src/apis/request/auth.ts
  client/src/apis/useFetch.ts
  client/src/components/MemberReportList/MemberReportList.tsx
  client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/AddMemberActionListModalContent.tsx
  client/src/components/Modal/SetActionModal/DeleteMemberActionModal/DeleteMemberActionModal.tsx
  client/src/components/Modal/SetInitialMemberListModal/SetInitialMemberListModal.tsx
  client/src/components/StepList/StepList.tsx
  client/src/constants/errorMessage.ts
  client/src/constants/password.ts
  client/src/hooks/useAuth.tsx
  client/src/hooks/useAuth/useAuth.test.tsx
  client/src/hooks/useAuth/useAuth.tsx
  client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.test.tsx
  client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.tsx
  client/src/hooks/useDynamicBillActionInput.tsx
  client/src/hooks/useEvent/useEvent.test.tsx
  client/src/hooks/useEvent/useEvent.tsx
  client/src/hooks/useFetch/useFetch.test.tsx
  client/src/hooks/useFetch/useFetch.ts
  client/src/hooks/usePutAndDeleteBillAction.ts
  client/src/hooks/useSearchInMemberList.ts
  client/src/hooks/useSearchMemberReportList/useSearchMemberReportList.test.tsx
  client/src/hooks/useSearchMemberReportList/useSearchMemberReportList.tsx
  client/src/hooks/useSetAllMemberList.tsx
  client/src/hooks/useSetPassword.ts
  client/src/hooks/useStepList/useStepList.test.tsx
  client/src/hooks/useStepList/useStepList.tsx
  client/src/mocks/handlers.ts
  client/src/mocks/handlers/authHandlers.ts
  client/src/mocks/handlers/eventHandlers.ts
  client/src/mocks/handlers/reportHandlers.ts
  client/src/mocks/handlers/stepListHandler.ts
  client/src/mocks/handlers/testHandlers.ts
  client/src/mocks/invalidMemberStepList.json
  client/src/mocks/memberActionStepList.json
  client/src/mocks/reportList.json
  client/src/mocks/server.ts
  client/src/mocks/serverConstants.ts
  client/src/mocks/validValueForTest.ts
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/EventPage/AdminPage/EventLoginPage.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/pages/EventPage/HomePage/HomePage.tsx
  client/src/utils/captureError.ts
  client/src/utils/objectToQueryString.ts
  client/tsconfig.json
Labels: 🖥️ FE, 🔍 QC

#373 [BE] 요구사항 변경에 따른 지출 내역 추가, 지출 액션 삭제 API 수정
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetailRepository.java
  server/src/main/java/server/haengdong/domain/action/CurrentMembers.java
  server/src/main/java/server/haengdong/presentation/response/ActionsResponse.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
Labels: ⌨️ BE, ⚙️ feat

#377 [BE] 참여자별 정산 현황 조회 및 액션 이력 조회 수정
  server/src/main/java/server/haengdong/application/ActionService.java
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/application/response/ActionAppResponse.java
  server/src/main/java/server/haengdong/domain/action/BillAction.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetail.java
  server/src/main/java/server/haengdong/domain/action/MemberBillReport.java
  server/src/main/java/server/haengdong/presentation/response/ActionResponse.java
  server/src/test/java/server/haengdong/application/ActionServiceTest.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
  server/src/test/java/server/haengdong/domain/action/BillActionTest.java
  server/src/test/java/server/haengdong/domain/action/MemberBillReportTest.java
Labels: ⌨️ BE, 🚧 refactor

#378 [BE] 참여자 개별 지출 금액 수정 및 조회 기능 구현
  server/src/docs/asciidoc/billActionDetail.adoc
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/server/haengdong/application/BillActionDetailService.java
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/application/request/BillActionDetailUpdateAppRequest.java
  server/src/main/java/server/haengdong/application/request/BillActionDetailsUpdateAppRequest.java
  server/src/main/java/server/haengdong/application/response/BillActionDetailAppResponse.java
  server/src/main/java/server/haengdong/application/response/BillActionDetailsAppResponse.java
  server/src/main/java/server/haengdong/domain/action/BillAction.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetail.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetailRepository.java
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/main/java/server/haengdong/presentation/BillActionDetailController.java
  server/src/main/java/server/haengdong/presentation/request/BillActionDetailUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/request/BillActionDetailsUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/response/BillActionDetailResponse.java
  server/src/main/java/server/haengdong/presentation/response/BillActionDetailsResponse.java
  server/src/test/java/server/haengdong/application/BillActionDetailServiceTest.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
  server/src/test/java/server/haengdong/docs/BillActionDetailControllerDocsTest.java
  server/src/test/java/server/haengdong/presentation/BillActionDetailControllerTest.java
  server/src/test/java/server/haengdong/presentation/ControllerTestSupport.java
Labels: ⌨️ BE, ⚙️ feat

#383 [FE] 멤버 액션 삭제 훅 리팩토링
  client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx
  client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.test.tsx
  client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.tsx
Labels: 🖥️ FE, 🚧 refactor

#385 [FE] 이벤트 생성 페이지 리팩토링
  client/src/hooks/useSetEventName.ts
  client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
  client/src/pages/CreateEventPage/SetEventNamePage.tsx
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
Labels: 🖥️ FE, 🚧 refactor

#387 [FE] useError, useToast 테스트코드 작성
  client/jest.config.ts
  client/jest.setup.ts
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/ErrorProvider.tsx
  client/src/apis/fetcher.ts
  client/src/components/Modal/SetActionModal/DeleteMemberActionModal/DeleteMemberActionModal.tsx
  client/src/components/Toast/Toast.tsx
  client/src/errors/FetchError.ts
  client/src/hooks/useAuth/useAuth.test.tsx
  client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.test.tsx
  client/src/hooks/useError/ErrorProvider.tsx
  client/src/hooks/useError/useError.test.tsx
  client/src/hooks/useError/useError.tsx
  client/src/hooks/useEvent/useEvent.test.tsx
  client/src/hooks/useFetch/useFetch.test.tsx
  client/src/hooks/useFetch/useFetch.ts
  client/src/hooks/useSearchMemberReportList/useSearchMemberReportList.test.tsx
  client/src/hooks/useStepList/useStepList.test.tsx
  client/src/hooks/useToast/ToastProvider.tsx
  client/src/hooks/useToast/useToast.test.tsx
  client/src/hooks/useToast/useToast.tsx
  client/src/mocks/svg.ts
  client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/types/fetchErrorType.ts
  client/src/utils/captureError.ts
  client/src/utils/sendLogToSentry.ts
  client/tsconfig.json
Labels: 🖥️ FE, 🚧 refactor

#394 [BE] 예외 처리 및 로깅 형식 수정
  server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java
  server/src/main/java/server/haengdong/presentation/BillActionController.java
  server/src/main/java/server/haengdong/presentation/request/BillActionDetailsUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/request/BillActionsSaveRequest.java
  server/src/main/java/server/haengdong/presentation/request/MemberActionsSaveRequest.java
  server/src/main/java/server/haengdong/presentation/request/MemberNamesUpdateRequest.java
Labels: ⌨️ BE, ⚙️ feat

#395 [BE] 예외 처리 및 로깅 형식 수정
  server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java
Labels: ⌨️ BE, ⚙️ feat

#388 [FE] Zustand, react-query 도입 및 적용
  client/eslint.config.mjs
  client/jest.config.ts
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/apis/request/member.ts
  client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/AddMemberActionListModalContent.tsx
  client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx
  client/src/components/Modal/SetInitialMemberListModal/SetInitialMemberListModal.tsx
  client/src/components/StepList/StepList.tsx
  client/src/constants/queryKeys.ts
  client/src/hooks/queries/useRequestDeleteAllMemberList.ts
  client/src/hooks/queries/useRequestDeleteBillAction.ts
  client/src/hooks/queries/useRequestDeleteMemberAction.ts
  client/src/hooks/queries/useRequestGetAllMemberList.ts
  client/src/hooks/queries/useRequestGetCurrentInMemberList.ts
  client/src/hooks/queries/useRequestGetEventName.ts
  client/src/hooks/queries/useRequestGetMemberReportList.ts
  client/src/hooks/queries/useRequestGetStepList.ts
  client/src/hooks/queries/useRequestPostAuthentication.ts
  client/src/hooks/queries/useRequestPostBillList.ts
  client/src/hooks/queries/useRequestPostEvent.ts
  client/src/hooks/queries/useRequestPostLogin.ts
  client/src/hooks/queries/useRequestPostMemberList.ts
  client/src/hooks/queries/useRequestPutAllMemberList.ts
  client/src/hooks/queries/useRequestPutBillAction.ts
  client/src/hooks/useAuth/useAuth.test.tsx
  client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.test.tsx
  client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.tsx
  client/src/hooks/useEvent/useEvent.test.tsx
  client/src/hooks/useEvent/useEvent.tsx
  client/src/hooks/usePutAndDeleteBillAction.ts
  client/src/hooks/useSearchInMemberList.ts
  client/src/hooks/useSearchMemberReportList/useSearchMemberReportList.test.tsx
  client/src/hooks/useSearchMemberReportList/useSearchMemberReportList.tsx
  client/src/hooks/useSetAllMemberList.tsx
  client/src/hooks/useSetEventPasswordPage.ts
  client/src/hooks/useSetPassword.ts
  client/src/hooks/useStepList/useStepList.test.tsx
  client/src/hooks/useStepList/useStepList.tsx
  client/src/pages/CreateEventPage/SetEventNamePage.tsx
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/EventPage/AdminPage/EventLoginPage.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/pages/EventPage/HomePage/HomePage.tsx
  client/src/store/stepListStore.ts
  client/src/store/totalExpenseAmountStore.ts
  client/src/types/serviceType.ts
  client/src/utils/caculateExpense.ts
  client/src/utils/getEventIdByUrl.ts
  client/src/utils/groupActions.ts
  client/src/utils/stepListToActions.ts
  client/tsconfig.json
  client/webpack.common.mjs
Labels: 🖥️ FE, ⚙️ feat, 🚧 refactor, 🛠️ Setting

#396 [FE] Input이 완전히 비워지지 않는 버그
  client/src/hooks/useDynamicInput.tsx
  client/src/utils/validate/validateMemberName.ts
Labels: 🖥️ FE, 🚨 bug, High

#405 [BE] 수정된 지출 상세의 상태 저장
  server/src/main/java/server/haengdong/application/BillActionDetailService.java
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/application/request/BillActionDetailUpdateAppRequest.java
  server/src/main/java/server/haengdong/application/response/BillActionDetailAppResponse.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetail.java
  server/src/main/java/server/haengdong/presentation/request/BillActionDetailUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/response/BillActionDetailResponse.java
  server/src/test/java/server/haengdong/application/ActionServiceTest.java
  server/src/test/java/server/haengdong/application/BillActionDetailServiceTest.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
  server/src/test/java/server/haengdong/docs/BillActionDetailControllerDocsTest.java
  server/src/test/java/server/haengdong/domain/action/BillActionTest.java
  server/src/test/java/server/haengdong/domain/action/MemberBillReportTest.java
  server/src/test/java/server/haengdong/presentation/BillActionDetailControllerTest.java
  server/src/test/java/server/haengdong/support/fixture/Fixture.java
Labels: ⌨️ BE, 🚧 refactor

#401 [FE] 총액 업데이트 로직을 store안으로 이동
  client/src/hooks/queries/useRequestGetStepList.ts
  client/src/store/totalExpenseAmountStore.ts
Labels: 🖥️ FE, ⚙️ feat

#408 [FE] action 로그가 길어질 경우 배경색 높이가 잘리는 버그
  client/src/GlobalStyle.ts
Labels: 🖥️ FE, 🚨 bug

#409 [FE] 전체 인원 수정 '삭제' api 로직 롤백 수정
  client/src/hooks/useDynamicInput.tsx
  client/src/hooks/useInput.tsx
  client/src/hooks/useSetAllMemberList.tsx
Labels: 🖥️ FE, ⚙️ feat, 🚨 bug

#411 [FE] EditableItem.Input이 동적인 width를 갖도록 수정
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/components/EditableItem/EditableItem.Input.style.ts
  HDesign/src/components/EditableItem/EditableItem.Input.tsx
  HDesign/src/components/EditableItem/EditableItem.Input.type.ts
  HDesign/src/components/EditableItem/EditableItem.input.stories.tsx
  HDesign/src/components/EditableItem/EditableItem.stories.tsx
  HDesign/src/components/EditableItem/EditableItem.style.ts
  HDesign/src/components/EditableItem/EditableItem.tsx
  HDesign/src/components/EditableItem/EditableItem.type.ts
  HDesign/src/type/withTheme.ts
  client/src/components/StepList/StepList.tsx
Labels: 🖥️ FE, ⚙️ feat, 🎨 Design

#420 [BE] 액션 이력 조회 stepName 추가
  server/src/main/java/server/haengdong/presentation/response/StepResponse.java
  server/src/main/java/server/haengdong/presentation/response/StepsResponse.java
  server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
  server/src/test/java/server/haengdong/presentation/response/StepsResponseTest.java
Labels: ⌨️ BE, ⚙️ feat

#406 [FE] 차등 정산 기능 구현 및 테스트 작성
  client/src/apis/request/bill.ts
  client/src/constants/queryKeys.ts
  client/src/hooks/queries/useRequestGetMemberReportListInAction.ts
  client/src/hooks/queries/useRequestPutMemberReportListInAction.ts
  client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.test.tsx
  client/src/hooks/useMemberReportListInAction/useMemberReportInput.tsx
  client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.test.tsx
  client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.ts
  client/src/mocks/handlers.ts
  client/src/mocks/handlers/memberReportInActionHandlers.ts
  client/src/mocks/handlers/stepListHandler.ts
  client/src/mocks/invalidMemberStepList.json
  client/src/mocks/memberActionStepList.json
  client/src/mocks/memberReportListInAction.json
  client/src/mocks/stepList.json
  client/src/types/serviceType.ts
  client/src/utils/validate/validateMemberReportInAction.ts
Labels: 🖥️ FE, ⚙️ feat

#423 [FE] 차등 적용 적용 중 지원되지 않는 기능 수정
  client/src/hooks/useMemberReportListInAction/useMemberReportInput.tsx
  client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.test.tsx
  client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.ts
  client/src/utils/validate/validateMemberReportInAction.ts
Labels: 🖥️ FE, ⚙️ feat

#428 [FE] 차등 적용 can submit이 valid 하지만 false되는 버그
  client/src/hooks/useMemberReportListInAction/useMemberReportInput.tsx
  client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.ts
Labels: 🖥️ FE, 🚨 bug, High

#414 [FE] 지출 내역 추가 변경사항 적용
  client/package-lock.json
  client/package.json
  client/src/components/StepList/BillStepItem.tsx
  client/src/components/StepList/Step.tsx
  client/src/components/StepList/StepList.tsx
  client/src/hooks/useSetBillInput.ts
  client/src/pages/EventPage/AdminPage/AdminPage.style.ts
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#433 [FE] BottomSheet 지출 부분 삭제 & input autoFocus
  client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.style.ts
  client/src/components/Modal/SetActionModal/AddBillActionListModalContent/AddBillActionListModalContent.tsx
  client/src/components/Modal/SetActionModal/AddBillActionListModalContent/index.ts
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/InMember.tsx
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/OutMember.tsx
  client/src/components/Modal/SetActionModal/SetActionListModal.tsx
  client/src/components/Modal/SetInitialMemberListModal/SetInitialMemberListModal.tsx
  client/src/components/StepList/StepList.tsx
  client/src/hooks/useDynamicBillActionInput.tsx
  client/src/hooks/usePutAndDeleteBillAction.ts
  client/src/hooks/useSetBillInput.ts
  client/src/types/serviceType.ts
Labels: 🖥️ FE, ⚙️ feat, 🚨 bug

#434 [FE] html height 100%
  client/src/GlobalStyle.ts
Labels: 🖥️ FE, ⚙️ feat, 🚨 bug

#435 [FE] 차등 적용 인원이 2명일 때 계산되지 않는 버그
  client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.test.tsx
  client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.ts
  client/src/mocks/handlers/memberReportInActionHandlers.ts
Labels: 🖥️ FE, 🚨 bug, High

#418 [FE] 랜딩페이지 구현
  client/cypress/e2e/createEvent.cy.ts
  client/src/assets/image/addBillMockup.svg
  client/src/assets/image/addMemberMockup.svg
  client/src/assets/image/chevronDownLarge.svg
  client/src/assets/image/memberReportMockup.svg
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/Nav/Nav.style.ts
  client/src/pages/MainPage/Nav/Nav.tsx
  client/src/pages/MainPage/Section/AddBillSection.tsx
  client/src/pages/MainPage/Section/AddMemberSection.tsx
  client/src/pages/MainPage/Section/DescriptionSection.tsx
  client/src/pages/MainPage/Section/MainSection.tsx
  client/src/pages/MainPage/Section/MemberReportSection.tsx
Labels: 🖥️ FE, ⚙️ feat, 🎨 Design

#438 [FE] 랜딩페이지 Nav 버그 수정
  client/src/hooks/useDynamicInput.tsx
  client/src/pages/MainPage/Nav/Nav.style.ts
  client/src/pages/MainPage/Nav/Nav.tsx
Labels: 🖥️ FE, 🚨 bug

#442 [FE] 전체 금액 수정 시 계산이 마이너스가 되는 문제
  client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx
Labels: 🖥️ FE, 🚨 bug, High

#443 [FE] 배경색상 height 버그
  client/src/GlobalStyle.ts
  client/src/pages/MainPage/Nav/Nav.style.ts
Labels: 🖥️ FE, 🚨 bug

#447 [FE] 배경 색 문제
  client/src/GlobalStyle.ts
Labels: 🖥️ FE, 🚨 bug, Medium

#448 [FE] 인원을 삭제했을 때 지출 상세 캐시 데이터 지우지 않는 문제
  client/src/hooks/queries/useRequestDeleteAllMemberList.ts
  client/src/hooks/queries/useRequestDeleteMemberAction.ts
  client/src/hooks/queries/useRequestPutAllMemberList.ts
Labels: 🖥️ FE, 🚨 bug, High

#455 [FE] 차등 정산 모달에서 수정 완료 버튼을 누를 때 보내는 2개의 api의 순서를 보장하고 변동이 없으면 요청을 보내지 않도록 함
  client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx
  client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.test.tsx
  client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.ts
  client/src/hooks/usePutAndDeleteBillAction.ts
Labels: 🖥️ FE, 🚨 bug

#452 [FE] Step에 stepName 반영하기
  client/src/components/StepList/BillStepItem.tsx
  client/src/components/StepList/StepList.tsx
Labels: 🖥️ FE, ⚙️ feat

#462 [FE] api 순서보장 await없어서 안됨
  client/src/hooks/usePutAndDeleteBillAction.ts
Labels: 🖥️ FE, 🚨 bug

#470 [FE] 지출 Input 금액 default 변경 및 autoFocus
  client/src/components/StepList/BillStepItem.tsx
Labels: 🖥️ FE, ⚙️ feat

#465 [FE] StepList에 isFixed 디자인시스템 반영
  HDesign/package-lock.json
  HDesign/package.json
  client/package-lock.json
  client/package.json
  client/src/components/StepList/BillStepItem.tsx
Labels: 🖥️ FE, ⚙️ feat, 🎨 Design

#458 [FE] 차등 정산 적용시 신선한 데이터가 바로 반영되지 않고 시간차를 두고 반영되는 부분 수정
  client/src/apis/request/bill.ts
  client/src/hooks/queries/useRequestDeleteAllMemberList.ts
  client/src/hooks/queries/useRequestPutAllMemberList.ts
  client/src/hooks/queries/useRequestPutMemberReportListInAction.ts
Labels: 🖥️ FE, 🚨 bug

#469 [FE] 관리자 로그인 페이지에서 스위치가 관리로 활성화되지 않는 버그
  client/src/hooks/useEventLogin.ts
  client/src/hooks/useNavSwitch.tsx
  client/src/pages/EventPage/AdminPage/EventLoginPage.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/router.tsx
Labels: 🖥️ FE, 🚨 bug, Low

#460 [BE] BillActionDetail 초기화시 totalPrice와 정합성 안맞는 버그 수정
  server/src/main/java/server/haengdong/application/BillActionDetailService.java
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/application/request/BillActionAppRequest.java
  server/src/main/java/server/haengdong/domain/action/BillAction.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetailRepository.java
Labels: ⌨️ BE, 🚨 bug

#466 [FE] 배경색아 제발
  HDesign/src/components/Flex/Flex.style.ts
  HDesign/src/components/Flex/Flex.type.ts
  HDesign/src/layouts/MainLayout.tsx
  client/src/GlobalStyle.ts
  client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
  client/src/pages/CreateEventPage/SetEventNamePage.tsx
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.style.ts
  client/src/pages/EventPage/HomePage/HomePage.tsx
Labels: 🖥️ FE, 🚨 bug

#472 [FE] title과 price에 값이 존재하지 않을 경우 지출 input 닫기
  client/src/hooks/useSetBillInput.ts
Labels: 🖥️ FE, ⚙️ feat

#476 [FE] 버튼 로딩 구현 및 이벤트 생성 페이지에 적용
  HDesign/eslint.config.mjs
  HDesign/package-lock.json
  HDesign/package.json
  HDesign/src/assets/loadingAnimation.json
  HDesign/src/components/Button/Button.stories.tsx
  HDesign/src/components/Button/Button.style.ts
  HDesign/src/components/Button/Button.tsx
  HDesign/src/components/Button/Button.type.ts
  HDesign/src/components/FixedButton/FixedButton.stories.tsx
  HDesign/src/components/FixedButton/FixedButton.style.ts
  HDesign/src/components/FixedButton/FixedButton.tsx
  HDesign/tsconfig.json
  client/package-lock.json
  client/package.json
  client/src/hooks/useError/useError.test.tsx
  client/src/hooks/useSetEventPasswordPage.ts
  client/src/hooks/useToast/useToast.test.tsx
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
Labels: 🖥️ FE, ⚙️ feat, 🎨 Design

#478 [FE] 행사 완료 페이지 간소화
  client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#480 [FE] 초기 인원 설정 시 placeholder 없던 오류 수정
  client/src/components/Modal/SetInitialMemberListModal/SetInitialMemberListModal.tsx
Labels: 🖥️ FE, ⚙️ feat

#491 [FE] 지출 내역 추가 시 금액에 숫자 외 다른 문자 입력 가능한 버그 수정
  client/src/components/StepList/BillStepItem.tsx
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
Labels: 🖥️ FE, 🚨 bug

#493 [FE] BottomSheet 애니메이션이 적용되지 않던 오류 수정
  client/src/components/StepList/BillStepItem.tsx
  client/src/components/StepList/MemberStepItem.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
Labels: 🖥️ FE, 🚨 bug, 🎨 Design

#463 [FE] React-Query devtools 환경 설정
  client/package-lock.json
  client/package.json
  client/src/App.tsx
Labels: 🖥️ FE, 🛠️ Setting

#335 [FE] amplitude 적용
  client/index.html
Labels: 🖥️ FE, 🛠️ Setting

#415 [FE] react-query에 맞는 error handling 적용
  client/jest.config.ts
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/apis/fetcher.ts
  client/src/components/AppErrorBoundary/ErrorCatcher.test.tsx
  client/src/components/AppErrorBoundary/ErrorCatcher.tsx
  client/src/components/QueryClientBoundary/QueryClientBoundary.tsx
  client/src/components/Toast/Toast.tsx
  client/src/components/Toast/Toast.type.ts
  client/src/hooks/useAuth/useAuth.test.tsx
  client/src/hooks/useAuth/useAuth.tsx
  client/src/hooks/useDeleteMemberAction/useDeleteMemberAction.test.tsx
  client/src/hooks/useError/ErrorProvider.tsx
  client/src/hooks/useError/useError.test.tsx
  client/src/hooks/useError/useError.tsx
  client/src/hooks/useEvent/useEvent.test.tsx
  client/src/hooks/useEvent/useEvent.tsx
  client/src/hooks/useFetch/useFetch.test.tsx
  client/src/hooks/useFetch/useFetch.ts
  client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.test.tsx
  client/src/hooks/useSearchMemberReportList/useSearchMemberReportList.test.tsx
  client/src/hooks/useSetEventNamePage.ts
  client/src/hooks/useToast/ToastProvider.tsx
  client/src/hooks/useToast/useToast.test.tsx
  client/src/pages/CreateEventPage/SetEventNamePage.tsx
  client/src/pages/ErrorPage/ErrorPage.tsx
  client/src/store/appErrorStore.ts
  client/src/types/fetchErrorType.ts
  client/src/utils/captureError.ts
  client/src/utils/sendLogToSentry.ts
Labels: 🖥️ FE, ⚙️ feat, 🚧 refactor

#498 [BE] 참여자 이름 변경시 지출 상세 이름 변경 안되는 버그 수정
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetail.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetailRepository.java
Labels: ⌨️ BE, 🚨 bug

#503 [FE] 비밀번호 4자리 넘게 적용되는 오류 수정
  HDesign/package-lock.json
  HDesign/package.json
  client/package-lock.json
  client/package.json
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
Labels: 🖥️ FE, ⚙️ feat, 🚨 bug

#506 [FE] bottomSheet 애니메이션 적용 롤백
  client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx
  client/src/components/StepList/MemberStepItem.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
Labels: 🖥️ FE, ⚙️ feat, 🚨 bug

#496 [FE] 행동대장 흔듯콘(파비콘), 로고 적용
  client/favicon.ico
  client/index.html
  client/src/assets/image/heundeut.svg
  client/src/assets/image/runningDog.svg
  client/src/assets/image/standingDog.svg
  client/src/components/Common/Logo/Logo.tsx
  client/src/components/Common/Logo/RunningDogLogo.tsx
  client/src/components/Common/Logo/StandingDogLogo.tsx
  client/src/components/Common/Logo/index.ts
  client/src/pages/CreateEventPage/CompleteCreateEventPage.tsx
  client/src/pages/MainPage/Nav/Nav.style.ts
  client/src/pages/MainPage/Nav/Nav.tsx
  client/src/pages/MainPage/Section/MainSection.tsx
  client/webpack.common.mjs
Labels: 🖥️ FE, ⚙️ feat

#510 [FE] meta tag 링크 복사 이미지와 설명 추가
  client/index.html
Labels: 🖥️ FE

#511 [FE] 지출 내역 및 전체 참여자 버그
  client/src/components/Modal/SetActionModal/AddMemberActionListModalContent/AddMemberActionListModalContent.tsx
  client/src/components/StepList/MemberStepItem.tsx
  client/src/components/StepList/StepList.tsx
  client/src/hooks/useDynamicInput.tsx
  client/src/hooks/useMemberReportListInAction/useMemberReportListInAction.test.tsx
  client/src/hooks/useSetAllMemberList.tsx
Labels: 🖥️ FE, 🚨 bug

#513 [FE] build를 위한 없는 파일 import 제거
  client/src/components/StepList/BillStepItem.tsx
  client/src/pages/MainPage/Nav/Nav.tsx
Labels: 🖥️ FE, 🚨 bug

#515 [FE] OG태그 이미지 해상도 변경
  client/index.html
Labels: 🖥️ FE, 🚨 bug

#520 [FE] 지출 내역이 없을 때 홈페이지에서 없다고 띄우기
  client/src/components/MemberReportList/MemberReportList.tsx
  client/src/components/StepList/StepList.tsx
  client/src/hooks/useSearchMemberReportList/useSearchMemberReportList.tsx
Labels: 🖥️ FE, ⚙️ feat

#525 [FE] 라이버러리 버전 업데이트
  client/package-lock.json
  client/package.json
Labels: 🖥️ FE, ⚙️ feat

#527 [FE] 프론트엔드 develop 브랜치로 merge
  HDesign/src/components/EditableItem/EditableItem.Input.tsx
  HDesign/src/components/EditableItem/EditableItem.stories.tsx
  client/package-lock.json
  client/package.json
  client/src/components/MemberReportList/MemberReportList.tsx
  client/src/components/Modal/SetActionModal/PutAndDeleteBillActionModal/PutAndDeleteBillActionModal.tsx
  client/src/components/StepList/StepList.tsx
  client/src/hooks/useSearchMemberReportList/useSearchMemberReportList.tsx
Labels: 🖥️ FE
