Repository woowacourse-teams/2024-haeng-dong, pull requests merged in 2024-12, with the labels that each got.

#837 [FE] 로그인 구축으로 인한 인증 전략 변경
  client/src/apis/request/auth.ts
  client/src/components/Design/components/TopNav/NavItem.tsx
  client/src/constants/routerUrls.ts
  client/src/constants/sessionStorageKeys.ts
  client/src/hooks/createEvent/useCreateGuestEventData.tsx
  client/src/hooks/queries/auth/useRequestPostAuthentication.ts
  client/src/hooks/queries/auth/useRequestPostLogin.ts
  client/src/hooks/queries/event/useRequestGetEvent.ts
  client/src/hooks/useAmplitude.ts
  client/src/hooks/useEventPageLayout.ts
  client/src/hooks/useLoginPage.ts
  client/src/hooks/useReportsPage.ts
  client/src/mocks/handlers/authHandlers.ts
  client/src/mocks/sharedState.ts
  client/src/pages/AccountPage/Account.tsx
  client/src/pages/CreateEventPage/CreateGuestEventPage/CreateGuestEventFunnel.tsx
  client/src/pages/EventPage/AuthGate/index.tsx
  client/src/pages/EventPage/EventPageFallback/Login/GusetEventLogin.tsx
  client/src/pages/EventPage/EventPageFallback/Login/MemberEventLogin.tsx
  client/src/pages/LoginPage/LoginFailFallback.tsx
  client/src/pages/LoginPage/LoginRedirectPage.tsx
  client/src/pages/LoginPage/index.tsx
  client/src/router.tsx
  client/src/types/serviceType.ts
  client/src/utils/SessionStorage.ts
  client/src/utils/getDeletedLastPath.ts
  client/src/utils/getEventBaseUrl.ts
Labels: 🖥️ FE, ⚙️ feat

#839 [FE] 마이페이지 화면 퍼블리싱
  client/src/constants/routerUrls.ts
  client/src/pages/MyPage/Container.tsx
  client/src/pages/MyPage/MyPage.style.ts
  client/src/pages/MyPage/index.tsx
  client/src/router.tsx
Labels: 🖥️ FE, ⚙️ feat

#842 [FE] 회원 행사 생성 endpoint가 맞지 않아 에러 발생됐던 원인 해결
  client/src/apis/request/event.ts
Labels: 🖥️ FE, 🚨 bug, High

#846 [BE] 내 행사 조회 기능 추가
  server/src/main/java/haengdong/event/application/EventService.java
  server/src/main/java/haengdong/event/application/request/EventMineAppResponse.java
  server/src/main/java/haengdong/event/domain/bill/MemberBillReport.java
  server/src/main/java/haengdong/event/domain/event/EventRepository.java
  server/src/main/java/haengdong/event/domain/event/member/EventMemberRepository.java
  server/src/main/java/haengdong/event/presentation/EventController.java
  server/src/main/java/haengdong/event/presentation/response/EventMineResponse.java
  server/src/main/java/haengdong/event/presentation/response/EventsMineResponse.java
  server/src/test/java/haengdong/domain/eventmember/EventMemberBillReportTest.java
Labels: ⌨️ BE, ⚙️ feat

#844 [FE] 계좌번호 수정이 되지 않는 문제 해결
  client/src/apis/request/event.ts
  client/src/hooks/queries/event/useRequestPatchEventName.ts
  client/src/hooks/queries/event/useRequestPatchUser.ts
  client/src/hooks/useAccount.ts
  client/src/types/serviceType.ts
Labels: 🖥️ FE, 🚨 bug, High

#852 [BE] 회원 정보 조회 기능 구현
  server/src/main/java/haengdong/event/application/EventService.java
  server/src/main/java/haengdong/event/application/response/UserAppResponse.java
  server/src/main/java/haengdong/event/domain/event/member/EventMember.java
  server/src/main/java/haengdong/user/application/KakaoUserService.java
  server/src/main/java/haengdong/user/application/UserService.java
  server/src/main/java/haengdong/user/application/request/UserJoinAppRequest.java
  server/src/main/java/haengdong/user/domain/User.java
  server/src/main/java/haengdong/user/presentation/UserController.java
  server/src/main/java/haengdong/user/presentation/response/UserResponse.java
Labels: ⌨️ BE, ⚙️ feat

#853 [FE] 이벤트 페이지 프로필 표시(로그인 유지) 및 이벤트 페이지 로딩 화면 설정
  client/src/apis/request/user.ts
  client/src/components/Design/components/Image/Image.tsx
  client/src/components/Design/components/Profile/Profile.stories.tsx
  client/src/components/Design/components/Profile/Profile.style.ts
  client/src/components/Design/components/Profile/Profile.tsx
  client/src/components/Design/components/Profile/Profile.type.ts
  client/src/components/Loader/EventLoader.tsx
  client/src/components/ShareEventButton/DesktopShareEventButton.tsx
  client/src/components/ShareEventButton/MobileShareEventButton.tsx
  client/src/constants/queryKeys.ts
  client/src/hooks/queries/user/useRequestGetUserInfo.ts
  client/src/hooks/useEventPageLayout.ts
  client/src/pages/EventPage/EventPageFallback/EventPageLoading.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/router.tsx
  client/src/types/serviceType.ts
Labels: 🖥️ FE, ⚙️ feat

#856 [FE] 생성한 행사 모아보기 페이지
  client/src/apis/request/event.ts
  client/src/components/Design/components/ChipGroup/ChipGroup.tsx
  client/src/components/Design/components/CreatedEvent/CreatedEvent.style.ts
  client/src/components/Design/components/CreatedEvent/CreatedEvent.tsx
  client/src/components/Design/components/CreatedEvent/CreatedEvent.type.ts
  client/src/constants/queryKeys.ts
  client/src/constants/routerUrls.ts
  client/src/hooks/queries/bill/useRequestGetBillDetails.ts
  client/src/hooks/queries/event/useRequestGetCreatedEvents.ts
  client/src/hooks/queries/event/useRequestGetEvent.ts
  client/src/hooks/queries/member/useRequestGetAllMembers.ts
  client/src/hooks/queries/member/useRequestGetCurrentMembers.ts
  client/src/hooks/queries/report/useRequestGetReports.ts
  client/src/hooks/queries/step/useRequestGetSteps.ts
  client/src/pages/CreatedEventsPage/CreatedEventsPage.tsx
  client/src/pages/MyPage/index.tsx
  client/src/router.tsx
  client/src/types/serviceType.ts
Labels: 🖥️ FE, ⚙️ feat

#857 [FE] 로그인 상태라면 행사 생성시 로그인 페이지를 띄우지 않음
  client/src/App.tsx
  client/src/apis/endpointPrefix.ts
  client/src/apis/request/auth.ts
  client/src/apis/request/event.ts
  client/src/components/QueryClientBoundary/QueryClientBoundary.tsx
  client/src/constants/queryKeys.ts
  client/src/errors/RequestGetError.ts
  client/src/hooks/queries/auth/useRequestGetUserInfo.ts
  client/src/mocks/handlers/authHandlers.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/Nav/Nav.tsx
  client/src/pages/MainPage/Section/MainSection/MainSection.tsx
  client/src/router.tsx
  client/src/types/serviceType.ts
Labels: 🖥️ FE, ⚙️ feat

#858 [FE] 회원탈퇴 페이지 퍼블리싱 및 api 연결
  client/src/apis/request/event.ts
  client/src/apis/request/user.ts
  client/src/assets/image/check.svg
  client/src/components/Design/components/Checkbox/Checkbox.stories.tsx
  client/src/components/Design/components/Checkbox/Checkbox.style.ts
  client/src/components/Design/components/Checkbox/Checkbox.tsx
  client/src/components/Design/components/Icon/Icon.style.ts
  client/src/components/Design/components/Textarea/Textarea.stories.tsx
  client/src/components/Design/components/Textarea/Textarea.style.ts
  client/src/components/Design/components/Textarea/Textarea.tsx
  client/src/components/Design/components/Textarea/Textarea.type.ts
  client/src/components/Design/index.tsx
  client/src/components/Logo/StandingDogLogo.tsx
  client/src/constants/routerUrls.ts
  client/src/hooks/queries/user/useRequestDeleteUser.ts
  client/src/hooks/useWithdrawFunnel.ts
  client/src/pages/MyPage/WithdrawPage/WithdrawPage.tsx
  client/src/pages/MyPage/WithdrawPage/steps/CheckBeforeWithdrawingStep.tsx
  client/src/pages/MyPage/WithdrawPage/steps/EtcStep.tsx
  client/src/pages/MyPage/WithdrawPage/steps/NotUseServiceStep.tsx
  client/src/pages/MyPage/WithdrawPage/steps/ReasonStep.style.ts
  client/src/pages/MyPage/WithdrawPage/steps/ReasonStep.tsx
  client/src/pages/MyPage/WithdrawPage/steps/UnableToUseDueToError.tsx
  client/src/pages/MyPage/WithdrawPage/steps/WithdrawalCompleted.tsx
  client/src/pages/MyPage/index.tsx
  client/src/router.tsx
Labels: 🖥️ FE, ⚙️ feat

#860 [FE] 행사 생성 시 관리자 이름 유효성 검사가 올바르게 수행되지 않는 버그와 그 외
  client/src/constants/errorMessage.ts
  client/src/hooks/createEvent/useSetNicknameStep.ts
  client/src/utils/validate/validateMemberName.ts
Labels: 🖥️ FE, 🚨 bug

#866 [FE] 이벤트 계좌번호 수정을 url로 진입할 경우 에러 발생하는 문제 해결
  client/src/hooks/useAccount.ts
  client/src/hooks/useAdminPage.ts
  client/src/pages/event/[eventId]/admin/AdminPage.tsx
  client/src/router.tsx
Labels: 🖥️ FE, 🚨 bug, High

#879 [BE] 행사 / 회원 계좌 번호 분리
  .idea/dataSources/a153963e-0410-4afc-ba3b-4e49c756008e/storage_v2/_src_/schema/haengdong.SSaEOA.meta
  server/src/main/java/haengdong/common/exception/HaengdongErrorCode.java
  server/src/main/java/haengdong/event/application/EventService.java
  server/src/main/java/haengdong/event/application/request/EventAppRequest.java
  server/src/main/java/haengdong/event/application/request/EventGuestAppRequest.java
  server/src/main/java/haengdong/event/application/request/EventUpdateAppRequest.java
  server/src/main/java/haengdong/event/application/request/MemberSaveAppRequest.java
  server/src/main/java/haengdong/event/application/request/MemberUpdateAppRequest.java
  server/src/main/java/haengdong/event/application/response/BillDetailAppResponse.java
  server/src/main/java/haengdong/event/application/response/EventDetailAppResponse.java
  server/src/main/java/haengdong/event/application/response/LastBillMemberAppResponse.java
  server/src/main/java/haengdong/event/application/response/MemberAppResponse.java
  server/src/main/java/haengdong/event/application/response/MemberBillReportAppResponse.java
  server/src/main/java/haengdong/event/application/response/MemberDepositAppResponse.java
  server/src/main/java/haengdong/event/application/response/MemberSaveAppResponse.java
  server/src/main/java/haengdong/event/application/response/UserAppResponse.java
  server/src/main/java/haengdong/event/domain/event/Event.java
  server/src/main/java/haengdong/event/domain/event/Password.java
  server/src/main/java/haengdong/event/domain/event/member/EventMember.java
  server/src/main/java/haengdong/event/domain/event/member/EventUniqueMembers.java
  server/src/main/java/haengdong/event/domain/event/member/UpdatedMembers.java
  server/src/main/java/haengdong/event/presentation/admin/AdminEventController.java
  server/src/main/java/haengdong/event/presentation/request/EventUpdateRequest.java
  server/src/main/java/haengdong/event/presentation/request/MemberUpdateRequest.java
  server/src/main/java/haengdong/event/presentation/request/MembersSaveRequest.java
  server/src/main/java/haengdong/event/presentation/response/BillDetailResponse.java
  server/src/main/java/haengdong/event/presentation/response/EventDetailResponse.java
  server/src/main/java/haengdong/event/presentation/response/MemberBillReportResponse.java
  server/src/main/java/haengdong/event/presentation/response/MemberDepositResponse.java
  server/src/main/java/haengdong/event/presentation/response/MemberResponse.java
  server/src/main/java/haengdong/event/presentation/response/MemberSaveResponse.java
  server/src/main/java/haengdong/user/application/UserService.java
  server/src/main/java/haengdong/user/domain/AccountNumber.java
  server/src/main/java/haengdong/user/domain/Bank.java
  server/src/main/java/haengdong/user/domain/Nickname.java
  server/src/main/java/haengdong/user/domain/User.java
  server/src/main/java/haengdong/user/presentation/response/UserResponse.java
  server/src/test/java/haengdong/application/BillServiceTest.java
  server/src/test/java/haengdong/application/EventEventMemberServiceTest.java
  server/src/test/java/haengdong/application/EventServiceTest.java
  server/src/test/java/haengdong/docs/AdminEventControllerDocsTest.java
  server/src/test/java/haengdong/docs/AdminEventEventMemberControllerDocsTest.java
  server/src/test/java/haengdong/docs/BillControllerDocsTest.java
  server/src/test/java/haengdong/docs/EventControllerDocsTest.java
  server/src/test/java/haengdong/docs/EventEventMemberControllerDocsTest.java
  server/src/test/java/haengdong/domain/event/EventTest.java
  server/src/test/java/haengdong/domain/eventmember/UpdatedMembersTest.java
  server/src/test/java/haengdong/presentation/BillControllerTest.java
  server/src/test/java/haengdong/presentation/EventControllerTest.java
  server/src/test/java/haengdong/presentation/EventEventMemberControllerTest.java
  server/src/test/java/haengdong/presentation/admin/AdminEventControllerTest.java
  server/src/test/java/haengdong/presentation/admin/AdminEventEventMemberControllerTest.java
  server/src/test/java/haengdong/support/fixture/Fixture.java
  server/src/test/java/haengdong/user/domain/UserTest.java
Labels: ⌨️ BE, ⚙️ feat

#869 [FE] 마이페이지 기능 고도화 및 행사 이름 변경 기능 구현
  client/src/apis/request/event.ts
  client/src/components/Design/components/CreatedEvent/CreatedEvent.tsx
  client/src/constants/routerUrls.ts
  client/src/hooks/createEvent/useSetEventNameStep.ts
  client/src/hooks/queries/auth/useRequestGetUserInfo.ts
  client/src/hooks/queries/auth/useRequestSuspenseGetUserInfo.ts
  client/src/hooks/queries/event/useRequestPatchEvent.ts
  client/src/hooks/useAccount.ts
  client/src/pages/event/[eventId]/admin/AdminPage.tsx
  client/src/pages/event/[eventId]/admin/edit-event-name/EditEventNamePage.tsx
  client/src/pages/fallback/MyPageError.tsx
  client/src/pages/fallback/MyPageLoading.tsx
  client/src/pages/mypage/Container.tsx
  client/src/pages/mypage/MyPage.style.ts
  client/src/pages/mypage/MyPage.tsx
  client/src/router.tsx
  client/src/types/serviceType.ts
Labels: 🖥️ FE, ⚙️ feat

#873 [FE] 토스/카카오톡 앱이 없을 때 앱스토어로 이동할 수 있도록 개선
  client/src/hooks/useSendPage.ts
  client/src/utils/navigateApp.ts
Labels: 🖥️ FE, 🚨 bug, Medium

#875 [FE] 송금 페이지 url에 멤버 id 보이지 않게 변경
  client/src/constants/routerUrls.ts
  client/src/hooks/useReportsPage.ts
  client/src/pages/event/[eventId]/home/send/SendPage.tsx
  client/src/router.tsx
Labels: 🖥️ FE, 🚧 refactor

#877 [FE] EventLoader하위로 EditAccountPage를 옮겨 데이터를 유지하기 위한 로직을 제거
  client/src/apis/request/event.ts
  client/src/components/Loader/EventDataProvider.tsx
  client/src/components/Loader/EventLoader.tsx
  client/src/hooks/useAccount.ts
  client/src/hooks/useAdminPage.ts
  client/src/hooks/useEventDataContext.tsx
  client/src/hooks/useEventLoader.ts
  client/src/hooks/useEventPageLayout.ts
  client/src/hooks/useReportsPage.ts
  client/src/mocks/handlers/eventHandlers.ts
  client/src/pages/event/[eventId]/EventPageLayout.tsx
  client/src/pages/event/[eventId]/home/HomePage.tsx
  client/src/router.tsx
  client/src/types/serviceType.ts
Labels: 🖥️ FE, 🚧 refactor

#882 [FE] 올바른 엔드포인트를 사용하지 않는 문제
  client/src/apis/request/event.ts
Labels: 🖥️ FE, 🚨 bug
