Repository woowacourse-teams/2024-haeng-dong, pull requests merged in 2024-09, with the labels that each got.

#540 [BE] 관리자용 핸들러 메소드 리팩토링 및 Controller 메소드 위치 조정
  server/src/main/java/server/haengdong/config/AdminInterceptor.java
  server/src/main/java/server/haengdong/config/WebMvcConfig.java
  server/src/main/java/server/haengdong/presentation/ActionController.java
  server/src/main/java/server/haengdong/presentation/BillActionDetailController.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/main/java/server/haengdong/presentation/MemberActionController.java
  server/src/main/java/server/haengdong/presentation/admin/AdminBillActionController.java
  server/src/main/java/server/haengdong/presentation/admin/AdminEventController.java
  server/src/main/java/server/haengdong/presentation/admin/AdminMemberActionController.java
  server/src/test/java/server/haengdong/docs/ActionControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/AdminBillActionControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/AdminEventControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/AdminMemberActionControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/BillActionDetailControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/MemberActionControllerDocsTest.java
  server/src/test/java/server/haengdong/presentation/ActionControllerTest.java
  server/src/test/java/server/haengdong/presentation/BillActionDetailControllerTest.java
  server/src/test/java/server/haengdong/presentation/ControllerTestSupport.java
  server/src/test/java/server/haengdong/presentation/EventControllerTest.java
  server/src/test/java/server/haengdong/presentation/MemberActionControllerTest.java
  server/src/test/java/server/haengdong/presentation/admin/AdminBillActionControllerTest.java
  server/src/test/java/server/haengdong/presentation/admin/AdminEventControllerTest.java
  server/src/test/java/server/haengdong/presentation/admin/AdminMemberActionControllerTest.java
Labels: ⌨️ BE, 🚧 refactor

#542 [BE] action 도메인 삭제
  server/src/main/java/server/haengdong/application/ActionService.java
  server/src/main/java/server/haengdong/application/BillActionDetailService.java
  server/src/main/java/server/haengdong/application/BillActionService.java
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/application/MemberActionFactory.java
  server/src/main/java/server/haengdong/application/MemberActionService.java
  server/src/main/java/server/haengdong/application/request/BillActionAppRequest.java
  server/src/main/java/server/haengdong/application/request/MemberActionSaveAppRequest.java
  server/src/main/java/server/haengdong/application/response/ActionAppResponse.java
  server/src/main/java/server/haengdong/domain/action/Action.java
  server/src/main/java/server/haengdong/domain/action/ActionRepository.java
  server/src/main/java/server/haengdong/domain/action/BillAction.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetail.java
  server/src/main/java/server/haengdong/domain/action/BillActionDetailRepository.java
  server/src/main/java/server/haengdong/domain/action/BillActionRepository.java
  server/src/main/java/server/haengdong/domain/action/MemberAction.java
  server/src/main/java/server/haengdong/domain/action/MemberActionRepository.java
  server/src/main/java/server/haengdong/domain/action/MemberBillReport.java
  server/src/main/java/server/haengdong/domain/action/MemberGroupIdProvider.java
  server/src/main/java/server/haengdong/domain/action/Sequence.java
  server/src/main/java/server/haengdong/domain/event/Event.java
  server/src/main/java/server/haengdong/domain/event/EventStep.java
  server/src/main/java/server/haengdong/presentation/EventController.java
  server/src/test/java/server/haengdong/application/ActionServiceTest.java
  server/src/test/java/server/haengdong/application/BillActionDetailServiceTest.java
  server/src/test/java/server/haengdong/application/BillActionServiceTest.java
  server/src/test/java/server/haengdong/application/EventServiceTest.java
  server/src/test/java/server/haengdong/application/MemberActionFactoryTest.java
  server/src/test/java/server/haengdong/application/MemberActionServiceTest.java
  server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
  server/src/test/java/server/haengdong/domain/action/ActionTest.java
  server/src/test/java/server/haengdong/domain/action/BillActionTest.java
  server/src/test/java/server/haengdong/domain/action/CurrentMembersTest.java
  server/src/test/java/server/haengdong/domain/action/MemberBillReportTest.java
  server/src/test/java/server/haengdong/domain/action/SequenceTest.java
  server/src/test/java/server/haengdong/presentation/ControllerTestSupport.java
  server/src/test/java/server/haengdong/presentation/EventControllerTest.java
  server/src/test/java/server/haengdong/support/fixture/Fixture.java
Labels: ⌨️ BE, 🚧 refactor

#557 [BE] MemberAction 제거로 인한 Bill 도메인의 테스트 변경사항 반영 to feature/#546
  server/src/main/java/server/haengdong/domain/action/Bill.java
  server/src/main/java/server/haengdong/domain/action/BillDetailRepository.java
  server/src/main/java/server/haengdong/presentation/BillController.java
  server/src/test/java/server/haengdong/application/BillServiceTest.java
  server/src/test/java/server/haengdong/docs/AdminBillControllerDocsTest.java
  server/src/test/java/server/haengdong/docs/BillControllerDocsTest.java
  server/src/test/java/server/haengdong/presentation/BillControllerTest.java
  server/src/test/java/server/haengdong/presentation/admin/AdminBillControllerTest.java
  server/src/test/java/server/haengdong/support/fixture/Fixture.java
Labels: ⌨️ BE, 🚧 refactor

#572 [BE] 관리자 인증 불가 버그 수정
  server/src/main/java/server/haengdong/config/AdminInterceptor.java
  server/src/test/java/server/haengdong/config/AdminInterceptorTest.java
Labels: ⌨️ BE, 🚨 bug

#548 [FE] 초대하기 OS 공유 기능 추가
  client/cypress/e2e/createEvent.cy.ts
  client/cypress/support/commands.ts
  client/index.html
  client/src/App.tsx
  client/src/components/KakaoInitializer/KakaoInitializer.tsx
  client/src/components/ShareEventButton/ShareEventButton.tsx
  client/src/components/ShareEventButton/index.ts
  client/src/global.d.ts
  client/src/hooks/useEventPageLayout.ts
  client/src/hooks/useShareEvent.ts
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/types/kakao.d.ts
  client/src/utils/isMobileDevice.ts
Labels: 🖥️ FE, ⚙️ feat

#568 [FE] 네트워크 상태가 오프라인일 경우 토스트로 안내하는 기능
  client/src/App.tsx
  client/src/hooks/useToast/ToastProvider.tsx
  client/src/utils/NetworkStateCatcher.tsx
Labels: 🖥️ FE, ⚙️ feat

#555 [FE] 입금 상태를 관리하는 컴포넌트 DepositToggle 기능 구현
  client/src/components/Design/components/DepositToggle/DepositToggle.stories.tsx
  client/src/components/Design/components/DepositToggle/DepositToggle.style.ts
  client/src/components/Design/components/DepositToggle/DepositToggle.tsx
  client/src/components/Design/components/DepositToggle/DepositToggle.type.ts
  client/src/components/Design/components/Text/Text.style.ts
Labels: 🖥️ FE, ⚙️ feat, 🎨 Design

#570 [FE] 참여자 입금 상태, 참여자 이름 Chip 컴포넌트 구현
  client/src/assets/image/check.svg
  client/src/assets/image/x.svg
  client/src/components/Design/components/DepositCheck/DepositCheck.stories.tsx
  client/src/components/Design/components/DepositCheck/DepositCheck.style.ts
  client/src/components/Design/components/DepositCheck/DepositCheck.tsx
  client/src/components/Design/components/DepositCheck/DepositCheck.type.ts
  client/src/components/Design/components/Icon/Icon.stories.tsx
  client/src/components/Design/components/Icon/Icon.style.ts
  client/src/components/Design/components/Icon/Icon.tsx
  client/src/components/Design/components/Icon/Icon.type.ts
Labels: 🖥️ FE, ⚙️ feat

#567 [FE] 에러 발생 시 지역적인 error boundary를 사용할 수 있도록 에러 처리 방식 개선
  client/src/App.tsx
  client/src/UnPredictableErrorBoundary.tsx
  client/src/apis/fetcher.ts
  client/src/apis/request/bill.ts
  client/src/apis/request/event.ts
  client/src/apis/request/member.ts
  client/src/apis/request/report.ts
  client/src/apis/request/step.ts
  client/src/components/AppErrorBoundary/ErrorCatcher.test.tsx
  client/src/components/AppErrorBoundary/ErrorCatcher.tsx
  client/src/components/QueryClientBoundary/QueryClientBoundary.tsx
  client/src/errors/FetchError.ts
  client/src/errors/RequestError.ts
  client/src/errors/RequestGetError.ts
  client/src/errors/requestErrorType.ts
  client/src/hooks/queries/bill/useRequestGetBillDetails.ts
  client/src/hooks/queries/event/useRequestGetEvent.ts
  client/src/hooks/queries/member/useRequestGetAllMembers.ts
  client/src/hooks/queries/member/useRequestGetCurrentMembers.ts
  client/src/hooks/queries/report/useRequestGetReports.ts
  client/src/hooks/queries/step/useRequestGetSteps.ts
  client/src/hooks/useBillDetails/useBillDetails.ts
  client/src/hooks/useSetEventPasswordPage.ts
  client/src/types/fetchErrorType.ts
  client/src/utils/captureError.ts
  client/src/utils/isRequestError.ts
  client/src/utils/sendLogToSentry.ts
Labels: 🖥️ FE, ⚙️ feat

#295 [ALL] 서비스 소개글 작성
  README.md
Labels: 🛠️ Setting, Low

#581 [BE] Domain 패키지와 Exception 패키지간의 순환 참조 해결
  server/src/docs/asciidoc/bill.adoc
  server/src/docs/asciidoc/billDetail.adoc
  server/src/main/java/server/haengdong/application/EventService.java
  server/src/main/java/server/haengdong/application/MemberService.java
  server/src/main/java/server/haengdong/domain/bill/Bill.java
  server/src/main/java/server/haengdong/domain/bill/MemberBillReport.java
  server/src/main/java/server/haengdong/domain/event/Bank.java
  server/src/main/java/server/haengdong/domain/event/Event.java
  server/src/main/java/server/haengdong/domain/event/Password.java
  server/src/main/java/server/haengdong/domain/member/Member.java
  server/src/main/java/server/haengdong/exception/ErrorResponse.java
  server/src/main/java/server/haengdong/exception/GlobalExceptionHandler.java
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/main/java/server/haengdong/exception/HaengdongException.java
  server/src/test/java/server/haengdong/application/MemberServiceTest.java
  server/src/test/java/server/haengdong/docs/BillControllerDocsTest.java
  server/src/test/java/server/haengdong/domain/member/MemberBillReportTest.java
  server/src/test/java/server/haengdong/presentation/BillControllerTest.java
  server/src/test/java/server/haengdong/presentation/admin/AdminBillControllerTest.java
Labels: ⌨️ BE, 🚧 refactor

#577 [FE] 참여자 별 내역에서 토스로 송금 유도하는 기능 (마무리)
  client/src/apis/request/event.ts
  client/src/components/Design/components/BankSendButton/BankSelect.stories.tsx
  client/src/components/Design/components/BankSendButton/BankSendButton.style.ts
  client/src/components/Design/components/BankSendButton/BankSendButton.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.tsx
  client/src/components/Design/components/Icon/Icon.tsx
  client/src/components/Design/components/Input/Input.style.ts
  client/src/components/Design/components/Input/Input.tsx
  client/src/components/Design/components/Input/Input.type.ts
  client/src/components/Design/components/LabelInput/LabelInput.style.ts
  client/src/components/Design/components/LabelInput/LabelInput.tsx
  client/src/components/Design/components/LabelInput/LabelInput.type.ts
  client/src/components/Design/components/Top/Line.tsx
  client/src/components/Design/index.tsx
  client/src/components/Design/layouts/FunnelLayout.tsx
  client/src/components/Reports/Reports.tsx
  client/src/components/ShareEventButton/ShareEventButton.tsx
  client/src/constants/errorMessage.ts
  client/src/constants/queryKeys.ts
  client/src/constants/routerUrls.ts
  client/src/hooks/queries/event/useRequestGetEvent.ts
  client/src/hooks/queries/event/useRequestPatchEvent.ts
  client/src/hooks/useAccount.ts
  client/src/hooks/useEventPageLayout.ts
  client/src/hooks/useReportsPage.ts
  client/src/hooks/useShareEvent.ts
  client/src/mocks/handlers/eventHandlers.ts
  client/src/mocks/sharedState.ts
  client/src/pages/Account/Account.tsx
  client/src/pages/AccountPage/Account.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/router.tsx
  client/src/utils/getDeletedLastPath.ts
Labels: 🖥️ FE, ⚙️ feat

#579 [FE] 토스트 사용성 개선
  client/src/App.tsx
  client/src/components/AppErrorBoundary/ErrorCatcher.test.tsx
  client/src/components/AppErrorBoundary/ErrorCatcher.tsx
  client/src/components/Design/components/Title/Title.tsx
  client/src/components/ShareEventButton/ShareEventButton.tsx
  client/src/components/Toast/Toast.style.ts
  client/src/components/Toast/Toast.tsx
  client/src/components/Toast/Toast.type.ts
  client/src/components/Toast/ToastContainer.tsx
  client/src/hooks/useReportsPage.ts
  client/src/hooks/useToast/ToastProvider.tsx
  client/src/hooks/useToast/toast.ts
  client/src/hooks/useToast/toastEventManager.ts
  client/src/hooks/useToast/toastEventManager.type.ts
  client/src/hooks/useToast/useToast.test.tsx
  client/src/hooks/useToast/useToast.tsx
  client/src/pages/CreateEventPage/SetEventNamePage.tsx
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
  client/src/pages/MainPage/Section/MainSection.tsx
  client/src/types/toastType.ts
  client/src/utils/NetworkStateCatcher.tsx
Labels: 🖥️ FE, ⚙️ feat

#582 [FE] 이벤트 홈 화면 새로운 플로우로 교체 (참여자 별 정산, 전체 지출 내역), Dropdown 컴포넌트 구현
  client/src/components/Design/components/Dropdown/Dropdown.stories.tsx
  client/src/components/Design/components/Dropdown/Dropdown.style.ts
  client/src/components/Design/components/Dropdown/Dropdown.tsx
  client/src/components/Design/components/Dropdown/Dropdown.type.ts
  client/src/components/Design/components/Dropdown/DropdownButton.tsx
  client/src/components/Design/components/Dropdown/useDropdown.ts
  client/src/components/Design/components/ExpenseList/ExpenseList.stories.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.style.ts
  client/src/components/Design/components/ExpenseList/ExpenseList.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.type.ts
  client/src/components/Design/components/Flex/Flex.style.ts
  client/src/components/Design/components/Flex/Flex.tsx
  client/src/components/Design/components/Flex/Flex.type.ts
  client/src/components/Design/components/Input/Input.style.ts
  client/src/components/Design/components/Input/Input.tsx
  client/src/components/Design/components/Search/Search.stories.tsx
  client/src/components/Design/components/Search/Search.style.ts
  client/src/components/Design/components/Search/Search.tsx
  client/src/components/Design/components/Tabs/Tabs.style.ts
  client/src/components/Design/components/Tabs/Tabs.tsx
  client/src/components/Design/components/Title/Title.tsx
  client/src/components/Design/components/Title/Title.type.ts
  client/src/components/Design/index.tsx
  client/src/components/Design/theme/HDesignProvider.tsx
  client/src/components/Design/theme/theme.type.ts
  client/src/components/Design/token/zIndex.ts
  client/src/components/Reports/Reports.tsx
  client/src/components/ShareEventButton/ShareEventButton.tsx
  client/src/components/StepList/Steps.tsx
  client/src/hooks/useReportsPage.ts
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/EventPage/EventPageFallback/BillEmptyFallback/index.tsx
  client/src/pages/EventPage/EventPageFallback/fallbackText.ts
  client/src/pages/EventPage/HomePage/HomePage.style.ts
  client/src/pages/EventPage/HomePage/HomePage.tsx
Labels: 🖥️ FE, ⚙️ feat

#587 [FE] 지출 내역 생성하기 기능 추가
  client/src/apis/request/bill.ts
  client/src/apis/request/member.ts
  client/src/components/Design/components/NumberKeyboard/NumberKeyboard.tsx
  client/src/components/Design/components/NumberKeyboard/useNumberKeyboard.tsx
  client/src/constants/regExp.ts
  client/src/constants/routerUrls.ts
  client/src/hooks/queries/bill/useRequestPostBill.ts
  client/src/hooks/queries/member/useRequestPostMembers.ts
  client/src/hooks/useAddBillFunnel.ts
  client/src/hooks/useMembersStep.ts
  client/src/hooks/usePriceStep.ts
  client/src/hooks/useTitleStep.ts
  client/src/mocks/handlers/billHandler.ts
  client/src/pages/AddBillFunnel/AddBillFunnel.tsx
  client/src/pages/AddBillFunnel/steps/MembersStep.tsx
  client/src/pages/AddBillFunnel/steps/PriceStep.tsx
  client/src/pages/AddBillFunnel/steps/TitleStep.tsx
  client/src/pages/BillPage/AddBillFunnel.tsx
  client/src/router.tsx
  client/src/utils/validate/validatePurchase.ts
Labels: 🖥️ FE, ⚙️ feat

#591 [FE] 행사 생성 페이지에 퍼널 방식 적용
  client/cypress/e2e/createEvent.cy.ts
  client/cypress/support/commands.ts
  client/src/components/Design/components/TopNav/Back.tsx
  client/src/constants/routerUrls.ts
  client/src/hooks/queries/event/useRequestPostEvent.ts
  client/src/hooks/useCreateEventData.tsx
  client/src/hooks/useFunnel.tsx
  client/src/hooks/useSetEventNameStep.ts
  client/src/hooks/useSetEventPasswordPage.ts
  client/src/hooks/useSetEventPasswordStep.ts
  client/src/pages/CreateEventPage/CompleteCreateEventStep.tsx
  client/src/pages/CreateEventPage/CreateEventFunnel.tsx
  client/src/pages/CreateEventPage/SetEventNamePage.tsx
  client/src/pages/CreateEventPage/SetEventNameStep.tsx
  client/src/pages/CreateEventPage/SetEventPasswordPage.tsx
  client/src/pages/CreateEventPage/SetEventPasswordStep.tsx
  client/src/pages/CreateEventPage/index.ts
  client/src/pages/ErrorPage/ErrorPage.tsx
  client/src/pages/MainPage/Nav/Nav.tsx
  client/src/pages/MainPage/Section/MainSection.tsx
  client/src/router.tsx
  client/src/utils/validate/validateEventName.ts
Labels: 🖥️ FE, ⚙️ feat

#595 [FE] 전체 참여자 관리 페이지 구현
  client/src/apis/request/bill.ts
  client/src/assets/image/pencil_mini.svg
  client/src/assets/image/trash_mini.svg
  client/src/components/Design/components/DepositToggle/DepositToggle.stories.tsx
  client/src/components/Design/components/DepositToggle/DepositToggle.style.ts
  client/src/components/Design/components/DepositToggle/DepositToggle.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.stories.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.tsx
  client/src/components/Design/components/ExpenseList/ExpenseList.type.ts
  client/src/components/Design/components/FixedButton/FixedButton.style.ts
  client/src/components/Design/components/Icon/Icon.stories.tsx
  client/src/components/Design/components/Icon/Icon.style.ts
  client/src/components/Design/components/Icon/Icon.tsx
  client/src/components/Design/components/Icon/Icon.type.ts
  client/src/components/Design/index.tsx
  client/src/components/Reports/Reports.tsx
  client/src/constants/routerUrls.ts
  client/src/hooks/queries/bill/useRequestGetBillDetails.ts
  client/src/hooks/useEditBillActions.ts
  client/src/hooks/useEditBillPage.ts
  client/src/hooks/useEventMember.ts
  client/src/hooks/useReportsPage.ts
  client/src/hooks/useSearchReports/useSearchReports.tsx
  client/src/hooks/useSetAllMemberList.tsx
  client/src/mocks/sharedState.ts
  client/src/pages/CreateEventPage/CompleteCreateEventStep.tsx
  client/src/pages/EventPage/AdminPage/AdminPage.tsx
  client/src/pages/EventPage/AdminPage/EventMemberManage.style.ts
  client/src/pages/EventPage/AdminPage/EventMemberManage.tsx
  client/src/router.tsx
  client/src/types/serviceType.ts
  client/src/utils/validate/validateMemberName.ts
Labels: 🖥️ FE, ⚙️ feat

#608 [BE] 계좌 정보를 은행 정보과 계좌 번호로 분리해서 응답
  server/src/main/java/server/haengdong/application/response/EventDetailAppResponse.java
  server/src/main/java/server/haengdong/domain/event/Event.java
  server/src/main/java/server/haengdong/presentation/response/EventDetailResponse.java
  server/src/test/java/server/haengdong/application/EventServiceTest.java
  server/src/test/java/server/haengdong/docs/EventControllerDocsTest.java
  server/src/test/java/server/haengdong/domain/event/EventTest.java
  server/src/test/java/server/haengdong/presentation/EventControllerTest.java
Labels: ⌨️ BE, 🚨 bug

#598 [BE] N+1문제 fetch join으로 쿼리 최적화
  server/src/main/java/server/haengdong/domain/bill/Bill.java
  server/src/main/java/server/haengdong/domain/bill/BillDetailRepository.java
  server/src/main/java/server/haengdong/domain/bill/BillRepository.java
  server/src/test/java/server/haengdong/application/BillServiceTest.java
Labels: ⌨️ BE, ⚙️ feat

#610 [BE] 멤버 정보 수정 API 호출 버그 수정
  server/src/docs/asciidoc/member.adoc
  server/src/main/java/server/haengdong/application/MemberService.java
  server/src/main/java/server/haengdong/domain/member/Member.java
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/test/java/server/haengdong/application/MemberServiceTest.java
Labels: ⌨️ BE, 🚨 bug

#645 [BE] API 명세서에 작성된 예외 최신화 및 코드 수정
  server/src/main/java/server/haengdong/exception/HaengdongErrorCode.java
  server/src/main/java/server/haengdong/presentation/request/BillDetailUpdateRequest.java
  server/src/main/java/server/haengdong/presentation/request/MemberSaveRequest.java
  server/src/test/java/server/haengdong/application/MemberServiceTest.java
Labels: ⌨️ BE, 🚧 refactor

#602 [FE] 계좌번호 입력 확인 버튼 활성화가 되지 않는 버그, 빈 값일 때 새로운 값이 반영되지 않는 버그
  client/src/hooks/useAccount.ts
Labels: 🖥️ FE, 🚨 bug, High

#604 [FE] 홈에서 지출 상세 수정 가능한 버그
  client/src/components/StepList/Step.stories.tsx
  client/src/components/StepList/Step.tsx
  client/src/components/StepList/Steps.tsx
Labels: 🖥️ FE, 🚨 bug, High

#611 [FE] 입금 상태를 변경하고 '수정완료' 버튼 클릭 시, 중복 이름 버그 발생
  client/src/hooks/queries/member/useRequestDeleteMember.ts
  client/src/hooks/queries/member/useRequestPutMembers.ts
  client/src/hooks/useEventMember.ts
Labels: 🖥️ FE, 🚨 bug

#613 [FE] useEventMember 불필요한 상태 제거 및 렌더링 성능 개선
  client/src/hooks/useEventMember.ts
  client/src/pages/EventPage/AdminPage/EventMember.style.ts
  client/src/pages/EventPage/AdminPage/EventMember.tsx
  client/src/router.tsx
Labels: 🖥️ FE, 🚧 refactor

#624 [FE] Loading Button으로 인해 Layout이 깨지는 문제
  client/src/components/Design/components/FixedButton/FixedButton.tsx
Labels: 🖥️ FE, 🚨 bug, 🔍 QC

#627 [FE] 홈 관리 네비게이션에 랜딩페이지로 이동하는 기능 추가 및 TopNav 구조 개선
  client/src/components/Design/components/Icon/Icon.style.ts
  client/src/components/Design/components/Icon/Icon.tsx
  client/src/components/Design/components/Icon/Icon.type.ts
  client/src/components/Design/components/Switch/Switch.stories.tsx
  client/src/components/Design/components/Switch/Switch.style.ts
  client/src/components/Design/components/Switch/Switch.tsx
  client/src/components/Design/components/Switch/Switch.type.ts
  client/src/components/Design/components/TextButton/TextButton.tsx
  client/src/components/Design/components/TextButton/TextButton.type.ts
  client/src/components/Design/components/TopNav/Back.tsx
  client/src/components/Design/components/TopNav/NavItem.style.ts
  client/src/components/Design/components/TopNav/NavItem.tsx
  client/src/components/Design/components/TopNav/NavItem.type.ts
  client/src/components/Design/components/TopNav/TopNav.stories.tsx
  client/src/components/Design/components/TopNav/TopNav.style.ts
  client/src/components/Design/components/TopNav/TopNav.tsx
  client/src/components/Design/index.tsx
  client/src/components/Logo/Logo.style.ts
  client/src/components/Logo/RunningDogLogo.tsx
  client/src/components/Logo/StandingDogLogo.tsx
  client/src/components/Logo/index.ts
  client/src/hooks/useEventPageLayout.ts
  client/src/hooks/useNavSwitch.tsx
  client/src/pages/AccountPage/Account.tsx
  client/src/pages/AddBillFunnel/AddBillFunnel.tsx
  client/src/pages/CreateEventPage/CompleteCreateEventStep.tsx
  client/src/pages/CreateEventPage/CreateEventFunnel.tsx
  client/src/pages/EditBillPage/EditBillPage.tsx
  client/src/pages/EventPage/AdminPage/EventMember.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/pages/MainPage/Section/MainSection.tsx
Labels: 🖥️ FE, ⚙️ feat

#631 [FE] 지출 추가에서 입력된 금액이 없을 시 layout이 변경되는 문제
  client/src/components/AmountInput/AmountInput.tsx
Labels: 🖥️ FE, 🔍 QC, Low

#633 [FE] NumberKeyboardBottomSheet 영역에서 스크롤이 가능한 문제
  client/src/components/Design/components/NumberKeyboard/NumberKeyboardBottomSheet.tsx
  client/src/components/Design/components/NumberKeyboard/useNumberKeyboardBottomSheet.ts
Labels: 🖥️ FE, 🔍 QC

#636 [FE] 전체 참여자 관리: '수정 완료'시, Toast 띄우기
  client/src/hooks/useAccount.ts
  client/src/hooks/useEventMember.ts
  client/src/pages/EventPage/AdminPage/EventMember.tsx
Labels: 🖥️ FE, ⚙️ feat

#637 [FE] 지출 생성 시 나갔던 멤버를 다시 추가할 수 없는 오류
  client/src/hooks/useMembersStep.ts
Labels: 🖥️ FE, 🚨 bug, 🔍 QC

#638 [FE] 모바일 환경에서 Font가 제대로 적용되지 않는 문제
  client/src/GlobalStyle.ts
  client/src/components/Design/theme/GlobalStyle.ts
Labels: ⚙️ feat, 🚨 bug, 🔍 QC

#639 [FE] 모바일 환경에서 멤버 추가 시 전에 입력한 이름의 끝자리가 입력되는 문제
  client/src/hooks/useMembersStep.ts
  client/src/pages/AddBillFunnel/steps/MembersStep.tsx
Labels: 🖥️ FE, 🚨 bug, 🔍 QC

#641 [FE] 지출에 멤버가 1명일 때, 금액이 수정되는 오류
  client/src/hooks/useEditBillState.ts
Labels: 🖥️ FE, 🚨 bug, 🔍 QC

#640 [FE] 행사 이름 한글이 두 자 씩 입력되는 버그
  client/src/hooks/useFunnel.tsx
  client/src/hooks/useSetEventNameStep.ts
  client/src/pages/CreateEventPage/CreateEventFunnel.tsx
  client/src/pages/CreateEventPage/SetEventNameStep.tsx
Labels: 🖥️ FE, 🚨 bug

#632 [FE] 최신의 서버 에러 코드를 프론트에 업데이트하고, 사용자에게 보여지는 에러 메세지를 이해하기 쉽도록 수정
  client/cypress/e2e/createEvent.cy.ts
  client/src/components/Design/components/NumberKeyboard/NumberKeyboard.stories.tsx
  client/src/constants/errorMessage.ts
  client/src/constants/rule.ts
  client/src/hooks/useEditBillKeyboardAction.ts
  client/src/pages/AddBillFunnel/steps/PriceStep.tsx
  client/src/pages/CreateEventPage/SetEventPasswordStep.tsx
  client/src/pages/EventPage/AdminPage/EventLoginPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#648 [FE] GlobalStyle tnum 삭제
  client/src/GlobalStyle.ts
Labels: 🖥️ FE, 🔍 QC

#651 [FE] IOS 환경에서도 토스 송금 기능을 똑같이 이용할 수 있도록 설정
  client/src/components/Design/components/ExpenseList/ExpenseList.tsx
  client/src/components/ShareEventButton/ShareEventButton.tsx
  client/src/hooks/useReportsPage.ts
  client/src/utils/detectDevice.ts
  client/src/utils/isMobileDevice.ts
Labels: 🖥️ FE, 🚨 bug, 🔍 QC

#652 [FE] merge 진행하면서 put, delete 요청 순서 보장 사라짐 + 수정 완료 Toast 없어짐 추가
  client/cypress/e2e/createEvent.cy.ts
  client/src/components/Design/components/NumberKeyboard/NumberKeyboardBottomSheet.tsx
  client/src/components/Design/components/TopNav/TopNav.style.ts
  client/src/components/Design/components/TopNav/TopNav.tsx
  client/src/components/ShareEventButton/ShareEventButton.tsx
  client/src/constants/message.ts
  client/src/hooks/useEventMember.ts
  client/src/pages/EventPage/AdminPage/EventMember.tsx
  client/src/pages/EventPage/EventPageLayout.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/Nav/Nav.tsx
Labels: 🖥️ FE, 🚨 bug

#653 [FE] 멤버 추가 시 제대로 작동하지 않는 문제 수정
  client/src/hooks/useMembersStep.ts
Labels: 🖥️ FE, 🚨 bug, 🔍 QC

#655 [FE] login 페이지 레이아웃 오류
  client/src/pages/EventPage/AdminPage/EventLoginPage.tsx
Labels: 🖥️ FE, 🚨 bug, 🔍 QC

#644 [BE] 행사 참여자 전체 수정 로직 리펙토링
  .github/workflows/backend-prod.yml
  server/src/main/java/server/haengdong/application/MemberService.java
  server/src/main/java/server/haengdong/application/request/MembersUpdateAppRequest.java
  server/src/main/java/server/haengdong/domain/bill/BillDetailRepository.java
  server/src/main/java/server/haengdong/domain/bill/BillRepository.java
  server/src/main/java/server/haengdong/domain/member/UpdatedMembers.java
  server/src/main/resources/application.yml
  server/src/test/java/server/haengdong/application/BillServiceTest.java
  server/src/test/java/server/haengdong/application/MemberServiceTest.java
  server/src/test/java/server/haengdong/domain/member/UpdatedMembersTest.java
Labels: ⌨️ BE, 🚧 refactor

#661 [FE] 멤버 추가 시 제대로 작동하지 않는 문제 수정
  client/src/components/Design/components/Input/Input.tsx
  client/src/hooks/useMembersStep.ts
Labels: 🖥️ FE, 🚨 bug, 🔍 QC

#670 [FE] 지출 내역 100만원 이상 등록이 되지 않는 버그
  client/src/hooks/useMembersStep.ts
Labels: 🚨 bug, 🔍 QC, High

#672 [FE] 멤버 추가 시 제대로 작동하지 않는 문제 수정
  client/src/components/Design/components/Input/Input.style.ts
  client/src/components/Design/components/Input/Input.tsx
  client/src/components/Design/components/Input/Input.type.ts
  client/src/components/Design/components/LabelGroupInput/Element.tsx
  client/src/components/Design/components/LabelGroupInput/Element.type.ts
  client/src/components/Design/components/LabelGroupInput/GroupInputContext.tsx
  client/src/components/Design/components/LabelGroupInput/LabelGroupInput.stories.tsx
  client/src/components/Design/components/LabelGroupInput/LabelGroupInput.style.ts
  client/src/components/Design/components/LabelGroupInput/LabelGroupInput.tsx
  client/src/components/Design/components/LabelGroupInput/LabelGroupInput.type.ts
  client/src/components/Design/components/LabelGroupInput/index.ts
  client/src/components/Design/components/LabelInput/LabelInput.stories.tsx
  client/src/components/Design/components/LabelInput/LabelInput.style.ts
  client/src/components/Design/components/LabelInput/LabelInput.tsx
  client/src/components/Design/components/LabelInput/LabelInput.type.ts
  client/src/components/Design/components/LabelInput/useLabelInput.ts
  client/src/components/Design/index.tsx
  client/src/hooks/useMembersStep.ts
  client/src/pages/AccountPage/Account.tsx
  client/src/pages/AddBillFunnel/steps/MembersStep.tsx
  client/src/pages/AddBillFunnel/steps/TitleStep.tsx
  client/src/pages/CreateEventPage/SetEventNameStep.tsx
  client/src/pages/CreateEventPage/SetEventPasswordStep.tsx
  client/src/pages/EventPage/AdminPage/EventLoginPage.tsx
Labels: 🖥️ FE, 🚨 bug, 🔍 QC

#659 [FE] 성능 개선할 수 있는 부분을 일부 개선
  .gitmodules
  client/package-lock.json
  client/package.json
  client/src/assets/image/Toss_Symbol_Primary.png
  client/src/assets/image/addBillMockup.svg
  client/src/assets/image/addMemberMockup.svg
  client/src/assets/image/heundeut.svg
  client/src/assets/image/memberReportMockup.svg
  client/src/assets/image/runningDog.svg
  client/src/assets/image/standingDog.svg
  client/src/components/Design/components/Button/Button.tsx
  client/src/components/Design/components/FixedButton/FixedButton.tsx
  client/src/components/Design/components/Icon/Icon.tsx
  client/src/components/Design/components/Lottie/Lottie.style.ts
  client/src/components/Design/components/Lottie/Lottie.tsx
  client/src/components/Design/components/NumberKeyboard/NumberKeyboard.tsx
  client/src/components/Design/components/Text/Text.tsx
  client/src/components/Design/index.tsx
  client/src/components/Design/token/colors.ts
  client/src/components/Logo/RunningDogLogo.tsx
  client/src/components/Logo/StandingDogLogo.tsx
  client/src/components/Toast/Toast.tsx
  client/src/global.d.ts
  client/src/mocks/handlers/eventHandlers.ts
  client/src/pages/EventPage/AdminPage/EventMember.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/Nav/Nav.tsx
  client/src/pages/MainPage/Section/AddBillSection.tsx
  client/src/pages/MainPage/Section/AddMemberSection.tsx
  client/src/pages/MainPage/Section/DescriptionSection.tsx
  client/src/pages/MainPage/Section/MainSection.tsx
  client/src/pages/MainPage/Section/ReportSection.tsx
  client/src/router.tsx
  client/webpack.common.mjs
  client/webpack.dev.mjs
Labels: 🖥️ FE, ⚙️ feat

#676 [FE] 입금 완료를 했는데 송금 버튼이 눌리는 버그
  client/src/components/Design/components/ExpenseList/ExpenseList.tsx
Labels: 🖥️ FE, 🚨 bug, 🔍 QC, High

#677 [FE] 지출 생성 시 나갔던 멤버를 다시 추가할 수 없는 오류
  client/src/hooks/useMembersStep.ts
Labels: 🖥️ FE, 🚨 bug, 🔍 QC

#679 [FE] 관리 입장시 잘못된 비밀번호 입력하면 '알수 없는 페이지'로 이동함
  client/src/constants/errorMessage.ts
Labels: 🖥️ FE, 🚨 bug, High
