Repository woowacourse-teams/2024-haeng-dong, pull requests merged in 2025-02, with the labels that each got.

#960 [FE] Checkbox component 변경
  client/src/components/Design/components/Checkbox/Checkbox.stories.tsx
  client/src/components/Design/components/Checkbox/Checkbox.style.ts
  client/src/components/Design/components/Checkbox/Checkbox.tsx
  client/src/components/Design/components/Checkbox/Checkbox.type.ts
  client/src/components/Design/components/CreatedEventItem/CreatedEventItem.tsx
  client/src/components/Design/utils/attribute.ts
  client/src/pages/setting/withdraw/NotUseServiceStep.tsx
  client/src/pages/setting/withdraw/UnableToUseDueToError.tsx
Labels: 🖥️ FE, ⚙️ feat, 🚨 bug

#964 [BE] 인원 수정 및 삭제 API 통합
  server/src/main/java/haengdong/event/application/EventMemberService.java
  server/src/main/java/haengdong/event/domain/event/member/UpdatedMembers.java
  server/src/test/java/haengdong/application/EventEventMemberServiceTest.java
  server/src/test/java/haengdong/domain/eventmember/UpdatedMembersTest.java
Labels: ⌨️ BE

#973 [FE] 에러 발생 시 에러 처리 시스템을 트리거하지 않고 무시할 수 있는 기능 추가
  client/src/apis/request/user.ts
  client/src/components/AppErrorBoundary/ErrorCatcher.tsx
  client/src/components/QueryClientBoundary/QueryClientBoundary.tsx
  client/src/errors/RequestGetError.ts
  client/src/hooks/queries/user/useRequestGetUserInfo.ts
Labels: 🖥️ FE, ⚙️ feat

#976 [FE] 메인 페이지에 TopNav 적용
  client/src/components/Design/components/ContentItem/ContentItem.tsx
  client/src/pages/main/MainPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#977 [FE] 은행 아이콘 이미지 변경 및 계좌번호 + 은행 아이콘 컴포넌트 제작
  client/.storybook/main.ts
  client/src/assets/image/largeBankSprites.svg
  client/src/components/AccountView/index.tsx
  client/src/components/Design/components/BankSelect/BankIcon.tsx
  client/src/components/Design/components/BankSelect/BankSelect.style.ts
  client/src/components/Design/components/BankSelect/BankSelect.tsx
  client/src/components/Design/components/BankSelect/BankSpriteInitializer.tsx
  client/src/constants/bank.ts
  client/src/pages/main/MainPage.tsx
  client/webpack.common.mjs
Labels: 🖥️ FE, ⚙️ feat

#979 Amplitude 사용자 트래킹 코드 고도화
  client/src/components/AmplitudeInitializer/AmplitudeInitializer.tsx
  client/src/components/CreatedEventList/index.tsx
  client/src/components/Design/components/Tabs/Tab.type.ts
  client/src/components/Design/components/Tabs/Tabs.tsx
  client/src/components/EditAccountPageView.tsx
  client/src/components/ShareEventButton/DesktopShareEventButton.tsx
  client/src/components/ShareEventButton/MobileShareEventButton.tsx
  client/src/hooks/queries/user/useRequestGetUserInfo.ts
  client/src/hooks/useAddImagesPage.ts
  client/src/hooks/useAmplitude.ts
  client/src/hooks/useEventMember.ts
  client/src/pages/event/[eventId]/EventPageLayout.tsx
  client/src/pages/event/[eventId]/admin/AdminPage.tsx
  client/src/pages/event/[eventId]/admin/edit-event-name/EditEventNamePage.tsx
  client/src/pages/event/[eventId]/home/HomePage.tsx
  client/src/pages/event/create/user/SetUserEventNameStep.tsx
  client/src/pages/landing/Section/CreatorSection/CreatorSection.tsx
  client/src/pages/landing/Section/CreatorSection/InViewportTrigger.tsx
  client/src/pages/main/edit-nickname/EditUserNicknamePage.tsx
  client/src/pages/setting/withdraw/CheckBeforeWithdrawingStep.tsx
  client/src/store/amplitudeStore.ts
  client/src/store/authStore.ts
Labels: 🖥️ FE, ⚙️ feat

#987 [FE] 로그인 후 행사 생성이 아닌 메인 페이지로 이동
  client/src/pages/login/LoginRedirectPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#988 [FE] main 페이지 연결
  client/src/pages/event/[eventId]/EventPageLayout.tsx
  client/src/pages/landing/Nav/Nav.tsx
  client/src/pages/landing/Section/MainSection/MainSection.tsx
Labels: 🖥️ FE, ⚙️ feat

#981 [FE] Tabs 컴포넌트 리팩터링
  client/src/components/Design/components/Tabs/Tab.tsx
  client/src/components/Design/components/Tabs/Tab.type.ts
  client/src/components/Design/components/Tabs/Tabs.stories.tsx
  client/src/components/Design/components/Tabs/Tabs.style.ts
  client/src/components/Design/components/Tabs/Tabs.tsx
  client/src/components/Design/components/Tabs/useTabContext.ts
  client/src/components/Design/components/Tabs/useTabIndicatorWidthInitializer.ts
  client/src/pages/event/[eventId]/home/HomePage.tsx
Labels: 🖥️ FE, 🚧 refactor

#991 [FE] 머지하면서 잘못 병합된 코드 해결
  client/src/pages/event/[eventId]/EventPageLayout.tsx
Labels: 🖥️ FE, 🚨 bug, High

#993 [FE] Bank icon 설정이 되어있지 않을 때 오류 해결
  client/src/components/AccountView/index.tsx
  client/src/components/Design/components/Stack/HStack.tsx
  client/src/components/Design/components/Stack/Stack.style.ts
  client/src/components/Design/components/Stack/Stack.tsx
  client/src/components/Design/components/Stack/VStack.tsx
Labels: 🖥️ FE, 🚨 bug, High

#996 [FE] 링크 공유 시 참여자 이름 넣기
  client/src/hooks/useEventPageLayout.ts
  client/src/hooks/useShareEvent.ts
  client/src/pages/event/[eventId]/EventPageLayout.tsx
Labels: 🖥️ FE, ⚙️ feat

#998 [FE] index.html og image를 우리 s3에서 가져오도록 변경
  client/index.html
Labels: 🖥️ FE, 🚧 refactor
