Repository woowacourse-teams/2024-haeng-dong, pull requests merged in 2025-01, with the labels that each got.

#886 [FE] 앱 설치 되어있음에도 deep link 대체 링크가 실행되는 버그 해결
  client/src/hooks/useNavigateApp.ts
  client/src/hooks/useSendPage.ts
  client/src/utils/navigateApp.ts
Labels: 🖥️ FE, 🚨 bug, High

#888 [FE] 행사 계좌 번호 수정 api 연결
  client/src/apis/endpointPrefix.ts
  client/src/apis/request/event.ts
  client/src/pages/event/[eventId]/admin/edit-account/EditAccountPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#889 [FE] 참여한 사람 입력 시 자음이 분리되는 버그와 리펙터링
  client/src/constants/errorMessage.ts
  client/src/constants/rule.ts
  client/src/hooks/createEvent/useCreateGuestEventData.tsx
  client/src/hooks/createEvent/useSetNicknameStep.ts
  client/src/hooks/useMemberName.ts
  client/src/hooks/useMembersStep.ts
  client/src/pages/event/create/guest/CreateGuestEventFunnel.tsx
  client/src/pages/event/create/guest/SetNickNameStep.tsx
  client/src/utils/isDuplicate.ts
  client/src/utils/validate/validateMemberName.ts
Labels: 🖥️ FE, 🚧 refactor, 🚨 bug

#870 [FE] Frontend CD 환경 재구축
  .github/workflows/frontend-dev-deploy.yml
  .github/workflows/frontend-prod-deploy.yml
Labels: 🖥️ FE, 🛠️ Setting

#901 [BE] 행사 삭제 기능 구현
  server/src/main/java/haengdong/event/application/EventService.java
  server/src/main/java/haengdong/event/application/request/EventDeleteAppRequest.java
  server/src/main/java/haengdong/event/domain/event/Event.java
  server/src/main/java/haengdong/event/presentation/EventController.java
  server/src/main/java/haengdong/event/presentation/request/EventDeleteRequest.java
  server/src/main/resources/logback-spring.xml
Labels: ⌨️ BE, ⚙️ feat

#903 [FE] 행사 삭제 기능 구현
  client/src/apis/request/event.ts
  client/src/components/CreatedEventList/index.tsx
  client/src/components/Design/components/Checkbox/Checkbox.tsx
  client/src/components/Design/components/CreatedEvent/CreatedEvent.style.ts
  client/src/components/Design/components/CreatedEvent/CreatedEvent.tsx
  client/src/components/Design/components/CreatedEvent/CreatedEvent.type.ts
  client/src/hooks/queries/event/useRequestDeleteEvents.ts
  client/src/hooks/queries/event/useRequestGetCreatedEvents.ts
  client/src/hooks/useAdminPage.ts
  client/src/hooks/useLongPressAnimation.tsx
  client/src/pages/event/[eventId]/admin/AdminPage.tsx
  client/src/pages/event/[eventId]/admin/edit-event-name/EditEventNamePage.tsx
  client/src/pages/mypage/events/CreatedEvent.context.tsx
  client/src/pages/mypage/events/CreatedEventsPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#904 [FE] Flex component 개선
  client/src/components/Design/components/Box/Box.stories.tsx
  client/src/components/Design/components/Box/Box.style.ts
  client/src/components/Design/components/Box/Box.tsx
  client/src/components/Design/components/Box/Box.type.ts
  client/src/components/Design/components/Container/Container.stories.tsx
  client/src/components/Design/components/Container/Container.style.ts
  client/src/components/Design/components/Container/Container.tsx
  client/src/components/Design/components/Container/Container.type.ts
  client/src/components/Design/components/Stack/HStack.stories.tsx
  client/src/components/Design/components/Stack/HStack.tsx
  client/src/components/Design/components/Stack/Stack.stories.tsx
  client/src/components/Design/components/Stack/Stack.style.ts
  client/src/components/Design/components/Stack/Stack.tsx
  client/src/components/Design/components/Stack/Stack.type.ts
  client/src/components/Design/components/Stack/VStack.stories.tsx
  client/src/components/Design/components/Stack/VStack.tsx
  client/src/components/Design/utils/attribute.ts
Labels: 🖥️ FE, ⚙️ feat, 🎨 Design

#906 [FE] 행사의 정산 완료가 제대로 표시되지 않는 문제
  client/src/components/Design/components/CreatedEvent/CreatedEvent.tsx
  client/src/hooks/queries/member/useRequestPutMembers.ts
Labels: 🖥️ FE, ⚙️ feat, 🚨 bug

#907 [FE] 홈에서 세부 정산 내역 페이지 구현
  client/src/components/BillDetails/BillDetails.tsx
  client/src/components/Design/components/Amount/EditableAmount.tsx
  client/src/components/Design/components/Tabs/Tab.type.ts
  client/src/components/Design/components/Tabs/Tabs.tsx
  client/src/components/StepList/Step.tsx
  client/src/constants/routerUrls.ts
  client/src/constants/sessionStorageKeys.ts
  client/src/pages/event/[eventId]/home/HomePage.tsx
  client/src/pages/event/[eventId]/home/bill-detail/BillDetailPage.tsx
  client/src/router.tsx
Labels: 🖥️ FE, ⚙️ feat

#909 [FE] 마이페이지에서 계좌 수정 페이지 연결
  client/src/pages/mypage/MyPage.tsx
Labels: 🖥️ FE, ⚙️ feat

#913 [FE] 회원탈퇴 Google 스프레드시트 api 연결 (실패와 실패 사유 및 간단 작업)
  client/src/hooks/queries/user/useRequestDeleteUser.ts
  client/src/hooks/useWithdrawFunnel.ts
  client/src/pages/mypage/withdraw/CheckBeforeWithdrawingStep.tsx
  client/src/pages/mypage/withdraw/WithdrawPage.tsx
  client/src/pages/mypage/withdraw/WithdrawalCompleted.tsx
Labels: 🖥️ FE, ⚙️ feat

#918 [FE] CD 환경 변수 설정 버그 수정
  .github/workflows/frontend-dev-deploy.yml
  .github/workflows/frontend-prod-deploy.yml
Labels: 🖥️ FE, 🚨 bug, High

#917 [FE] 카카오 로그인 프로필 연동을 선택하지 않을 경우 프로필 이미지 alt로 띄워지는 문제
  client/src/pages/event/[eventId]/EventPageLayout.tsx
  client/src/pages/mypage/MyPage.tsx
Labels: 🖥️ FE, 🚨 bug

#923 [FE] api 호출 개선 : 지출 내역 과정
  client/src/hooks/queries/bill/useRequestDeleteBill.ts
  client/src/hooks/queries/bill/useRequestPostBill.ts
  client/src/hooks/queries/bill/useRequestPutBill.ts
  client/src/hooks/queries/bill/useRequestPutBillDetails.ts
  client/src/hooks/queries/member/useRequestPostMembers.ts
  client/src/hooks/useEditBillActions.ts
Labels: 🖥️ FE, 🚧 refactor

#924 [FE] api 호출 개선 : 이벤트 페이지 진입 시 같은 api 7개씩 호출되는 문제
  client/src/components/Loader/EventData/EventDataLoader.tsx
  client/src/components/Loader/EventData/EventDataProvider.tsx
  client/src/hooks/queries/auth/useRequestPostAuthentication.ts
  client/src/hooks/useAdminPage.ts
  client/src/hooks/useEventLoader.ts
  client/src/hooks/useEventPageLayout.ts
  client/src/hooks/useMembersStep.ts
  client/src/pages/event/[eventId]/home/HomePage.tsx
Labels: 🖥️ FE, 🚧 refactor

#925 [FE] 콘솔 화면 빨간색 경고 제거
  client/src/EssentialQueryApp.tsx
  client/src/apis/request/event.ts
  client/src/apis/request/images.ts
  client/src/components/Design/components/Amount/Amount.tsx
  client/src/components/Design/components/Button/Button.style.ts
  client/src/components/Design/components/Button/Button.tsx
  client/src/components/Design/components/FixedButton/FixedButton.style.ts
  client/src/components/Design/components/FixedButton/FixedButton.tsx
  client/src/components/Design/components/IconButton/IconButton.style.ts
  client/src/components/Design/components/Icons/Svg.tsx
  client/src/components/Design/components/Input/Input.stories.tsx
  client/src/components/Design/components/NumberKeyboard/NumberKeyboardBottomSheet.tsx
  client/src/components/Design/components/Tabs/Tabs.stories.tsx
  client/src/components/Design/components/TextButton/TextButton.style.ts
  client/src/components/ExpenseDetailModal/ExpenseDetailModal.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/StepList/Step.tsx
  client/src/hooks/queries/event/useRequestPostGuestEvent.ts
  client/src/hooks/useEditBillKeyboardAction.ts
  client/src/hooks/usePutAndDeleteBill.ts
  client/src/mocks/handlers/memberHandler.ts
  client/src/pages/event/[eventId]/admin/add-bill/MembersStep.tsx
  client/src/utils/NetworkStateCatcher.tsx
Labels: 🖥️ FE, 🚧 refactor

#927 [FE] Cypress 코드 정상화
  client/cypress/constants/constants.ts
  client/cypress/e2e/createEvent.cy.ts
  client/cypress/e2e/createEventByGuest.cy.ts
  client/cypress/support/commands.ts
Labels: 🖥️ FE, 🛠️ Setting

#928 [FE] 계좌번호 입력 제한 글자 수 세는 정책 변경
  client/src/hooks/useAccount.ts
  client/src/utils/validate/validateAccountNumber.ts
Labels: 🖥️ FE, ⚙️ feat

#929 [FE] API_BASE_URL에서 널 병합 연산자 제거
  client/src/apis/request.ts
Labels: 🖥️ FE, 🛠️ Setting

#931 [FE] api 호출 개선 : 전체 참여자 관리 과정
  client/src/hooks/queries/bill/useRequestDeleteBill.ts
  client/src/hooks/queries/bill/useRequestGetBillDetails.ts
  client/src/hooks/queries/bill/useRequestPutBillDetails.ts
  client/src/hooks/queries/event/useRequestPatchEvent.ts
  client/src/hooks/queries/images/useRequestDeleteImages.ts
  client/src/hooks/queries/images/useRequestGetImages.ts
  client/src/hooks/queries/images/useRequestPostImages.ts
  client/src/hooks/queries/member/useRequestDeleteMember.ts
  client/src/hooks/queries/member/useRequestPostMembers.ts
  client/src/hooks/queries/member/useRequestPutMembers.ts
  client/src/hooks/useEventPageLoader.ts
Labels: 🖥️ FE, 🚧 refactor

#935 [FE] 전체 참여자 관리 : 참여자 이름이 1개 남았을 경우 지울 수 없는 버그
  client/src/hooks/useEventMember.ts
  client/src/pages/event/[eventId]/admin/members/MemberPageType.ts
  client/src/pages/event/[eventId]/admin/members/MembersPage.style.ts
  client/src/pages/event/[eventId]/admin/members/MembersPage.tsx
Labels: 🖥️ FE, ⚙️ feat, 🚧 refactor, 🚨 bug, High

#938 [FE] 전체 참여자 관리 : input의 값이 유효하지 않을 경우 borderBottom을 error 컬러로 변경
  client/src/constants/errorMessage.ts
  client/src/hooks/useEventMember.ts
  client/src/pages/event/[eventId]/admin/members/Member.tsx
  client/src/pages/event/[eventId]/admin/members/MemberPageType.ts
  client/src/pages/event/[eventId]/admin/members/MembersPage.style.ts
  client/src/pages/event/[eventId]/admin/members/MembersPage.tsx
  client/src/utils/validate/validateMemberName.ts
Labels: 🖥️ FE, ⚙️ feat

#940 [FE] 스타일에 플레이스 홀더가 두개 들어가있는 문제 해결
  client/src/pages/event/[eventId]/admin/members/MembersPage.style.ts
Labels: 🖥️ FE, 🚨 bug, High

#942 [FE] 아이콘 적용 버그 문제 해결
  client/src/assets/image/setting.svg
  client/src/components/Design/components/Amount/EditableAmount.tsx
  client/src/components/Design/components/Banner/Banner.tsx
  client/src/components/Design/components/DepositCheck/DepositCheck.tsx
  client/src/components/Design/components/Icons/Icon.stories.tsx
  client/src/components/Design/components/Icons/Icons/IconSetting.tsx
  client/src/components/Design/components/Top/EditableLine.tsx
Labels: 🖥️ FE, ⚙️ feat, 🚨 bug

#945 [FE] 지출 내역 인원 변동 step으로 들어갈 때 provider 오류
  client/src/hooks/useMembersStep.ts
Labels: 🖥️ FE, 🚨 bug, High

#946 [FE] v3.1.2 배포
  client/src/hooks/useMembersStep.ts
Labels: 🖥️ FE

#948 [FE] iOS에서 아이콘이 제대로 보이지 않던 문제
  client/src/components/Design/components/Icons/Svg.style.ts
Labels: 🖥️ FE, 🚨 bug

#950 [FE] v3.1.3 배포
  client/src/components/Design/components/Icons/Svg.style.ts
Labels: 🖥️ FE, 🚨 bug

#952 [FE] 라운지 화면 구현
  client/src/components/CreatedEventList/index.tsx
  client/src/components/Design/components/ContentItem/ContentItem.stories.tsx
  client/src/components/Design/components/ContentItem/ContentItem.style.ts
  client/src/components/Design/components/ContentItem/ContentItem.tsx
  client/src/components/Design/components/ContentItem/ContentItem.type.ts
  client/src/components/Design/components/ContentLabel/ContentLabel.stories.tsx
  client/src/components/Design/components/ContentLabel/ContentLabel.tsx
  client/src/components/Design/components/ContentLabel/ContentLabel.type.ts
  client/src/components/Design/components/CreatedEventItem/CreatedEventItem.style.ts
  client/src/components/Design/components/CreatedEventItem/CreatedEventItem.tsx
  client/src/components/Design/components/CreatedEventItem/CreatedEventView.tsx
  client/src/constants/routerUrls.ts
  client/src/pages/event/[eventId]/EventPageLayout.tsx
  client/src/pages/event/create/user/CreateUserEventFunnel.tsx
  client/src/pages/fallback/EventEmptyFallback.tsx
  client/src/pages/fallback/LoungePageError.tsx
  client/src/pages/fallback/LoungePageLoading.tsx
  client/src/pages/lounge/Lounge.tsx
  client/src/pages/lounge/edit-account/EditUserAccountPage.tsx
  client/src/pages/lounge/edit-nickname/EditUserNicknamePage.tsx
  client/src/pages/lounge/events/CreatedEvent.context.tsx
  client/src/pages/lounge/events/CreatedEventsPage.tsx
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/mypage/withdraw/CheckBeforeWithdrawingStep.tsx
  client/src/pages/mypage/withdraw/EtcStep.tsx
  client/src/pages/mypage/withdraw/NotUseServiceStep.tsx
  client/src/pages/mypage/withdraw/ReasonStep.style.ts
  client/src/pages/mypage/withdraw/ReasonStep.tsx
  client/src/pages/mypage/withdraw/UnableToUseDueToError.tsx
  client/src/pages/mypage/withdraw/WithdrawPage.tsx
  client/src/pages/mypage/withdraw/WithdrawalCompleted.tsx
  client/src/router.tsx
Labels: 🖥️ FE, ⚙️ feat

#962 [FE] 설정 페이지 디자인 및 구현
  client/src/constants/routerUrls.ts
  client/src/pages/setting/SettingPage.tsx
  client/src/pages/setting/SettingPage.type.ts
  client/src/pages/setting/withdraw/CheckBeforeWithdrawingStep.tsx
  client/src/pages/setting/withdraw/EtcStep.tsx
  client/src/pages/setting/withdraw/NotUseServiceStep.tsx
  client/src/pages/setting/withdraw/ReasonStep.style.ts
  client/src/pages/setting/withdraw/ReasonStep.tsx
  client/src/pages/setting/withdraw/UnableToUseDueToError.tsx
  client/src/pages/setting/withdraw/WithdrawPage.tsx
  client/src/pages/setting/withdraw/WithdrawalCompleted.tsx
  client/src/router.tsx
Labels: 🖥️ FE, ⚙️ feat

#958 [FE] 카카오 로그인 상태일 때 상단에 보이는 프로필 이미지 제거
  client/src/pages/event/[eventId]/EventPageLayout.tsx
Labels: 🖥️ FE, ⚙️ feat

#954 [FE] Github PR create, close 할 때 관련 이슈 status 조정
  .github/auto_assign.yml
  .github/workflows/frontend-sync-issue-to-pr.yml
Labels: 🖥️ FE, 🛠️ Setting

#967 [FE] 이름 변경 글자수 서버 에러 메시지 버그 + 다양한 서버 에러 메세지 수정
  client/src/constants/errorMessage.ts
  client/src/constants/rule.ts
Labels: 🖥️ FE, 🚨 bug

#969 [FE] 회원 이름 변경 label 변경
  client/src/pages/lounge/edit-nickname/EditUserNicknamePage.tsx
Labels: 🖥️ FE, 🚨 bug

#971 [FE] 라운지 -> 메인, 메인 랜딩으로 디렉토리 변경
  client/cypress/e2e/createEventByGuest.cy.ts
  client/src/components/CreatedEventList/index.tsx
  client/src/components/Design/components/CreatedEventItem/CreatedEventItem.tsx
  client/src/components/Design/components/CreatedEventItem/CreatedEventView.tsx
  client/src/constants/routerUrls.ts
  client/src/pages/fallback/MainPageError.tsx
  client/src/pages/fallback/MainPageLoading.tsx
  client/src/pages/landing/LandingPage.style.ts
  client/src/pages/landing/LandingPage.tsx
  client/src/pages/landing/Nav/Nav.style.ts
  client/src/pages/landing/Nav/Nav.tsx
  client/src/pages/landing/Nav/index.ts
  client/src/pages/landing/Section/CreatorSection/Avatar.style.ts
  client/src/pages/landing/Section/CreatorSection/Avatar.tsx
  client/src/pages/landing/Section/CreatorSection/CreatorSection.style.ts
  client/src/pages/landing/Section/CreatorSection/CreatorSection.tsx
  client/src/pages/landing/Section/DescriptionSection/DescriptionSection.style.ts
  client/src/pages/landing/Section/DescriptionSection/DescriptionSection.tsx
  client/src/pages/landing/Section/DescriptionSection/index.ts
  client/src/pages/landing/Section/FeatureSection/AutoCalculate/AutoCalculate.style.ts
  client/src/pages/landing/Section/FeatureSection/AutoCalculate/AutoCalculate.tsx
  client/src/pages/landing/Section/FeatureSection/AutoCalculate/index.ts
  client/src/pages/landing/Section/FeatureSection/CheckDeposit/CheckDeposit.style.ts
  client/src/pages/landing/Section/FeatureSection/CheckDeposit/CheckDeposit.tsx
  client/src/pages/landing/Section/FeatureSection/CheckDeposit/index.ts
  client/src/pages/landing/Section/FeatureSection/FeatureSection.tsx
  client/src/pages/landing/Section/FeatureSection/RecordMemoryWithPhoto/RecordMemoryWithPhoto.style.ts
  client/src/pages/landing/Section/FeatureSection/RecordMemoryWithPhoto/RecordMemoryWithPhoto.tsx
  client/src/pages/landing/Section/FeatureSection/RecordMemoryWithPhoto/index.ts
  client/src/pages/landing/Section/FeatureSection/SimpleShare/SimpleShare.style.ts
  client/src/pages/landing/Section/FeatureSection/SimpleShare/SimpleShare.tsx
  client/src/pages/landing/Section/FeatureSection/SimpleShare/index.ts
  client/src/pages/landing/Section/FeatureSection/SimpleTransfer/SimpleTransfer.style.ts
  client/src/pages/landing/Section/FeatureSection/SimpleTransfer/SimpleTransfer.tsx
  client/src/pages/landing/Section/FeatureSection/SimpleTransfer/index.ts
  client/src/pages/landing/Section/FeatureSection/index.ts
  client/src/pages/landing/Section/MainSection/MainSection.style.ts
  client/src/pages/landing/Section/MainSection/MainSection.tsx
  client/src/pages/landing/Section/MainSection/index.ts
  client/src/pages/landing/index.ts
  client/src/pages/lounge/Lounge.tsx
  client/src/pages/main/MainPage.tsx
  client/src/pages/main/edit-account/EditUserAccountPage.tsx
  client/src/pages/main/edit-nickname/EditUserNicknamePage.tsx
  client/src/pages/main/events/CreatedEvent.context.tsx
  client/src/pages/main/events/CreatedEventsPage.tsx
  client/src/pages/main/index.ts
  client/src/pages/setting/SettingPage.tsx
  client/src/router.tsx
Labels: 🖥️ FE, ⚙️ feat
